package vavi.sound.midi.fluidsynth.jna.voice;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;
/**
 * JNA Wrapper for library <b>voice</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface VoiceLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "voice";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(VoiceLibrary.JNA_LIBRARY_NAME);
	public static final VoiceLibrary INSTANCE = (VoiceLibrary)Native.load(VoiceLibrary.JNA_LIBRARY_NAME, VoiceLibrary.class);
	/**
	 * Enum used with fluid_voice_add_mod() to specify how to handle duplicate modulators.<br>
	 * <i>native declaration : fluidsynth/voice.h:47</i><br>
	 * enum values
	 */
	public static interface fluid_voice_add_mod {
		/**
		 * < Overwrite any existing matching modulator<br>
		 * <i>native declaration : fluidsynth/voice.h:49</i>
		 */
		public static final int FLUID_VOICE_OVERWRITE = 0;
		/**
		 * < Add (sum) modulator amounts<br>
		 * <i>native declaration : fluidsynth/voice.h:50</i>
		 */
		public static final int FLUID_VOICE_ADD = 1;
		/**
		 * < For default modulators only, no need to check for duplicates<br>
		 * <i>native declaration : fluidsynth/voice.h:51</i>
		 */
		public static final int FLUID_VOICE_DEFAULT = 2;
	};
	/**
	 * Original signature : <code>void fluid_voice_add_mod(fluid_voice_t*, fluid_mod_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:54</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_add_mod(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	void fluid_voice_add_mod(Pointer voice, Pointer mod, int mode);
	/**
	 * Original signature : <code>void fluid_voice_add_mod(fluid_voice_t*, fluid_mod_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:54</i>
	 */
	void fluid_voice_add_mod(PointerByReference voice, PointerByReference mod, int mode);
	/**
	 * Original signature : <code>float fluid_voice_gen_get(fluid_voice_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:55</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_gen_get(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	float fluid_voice_gen_get(Pointer voice, int gen);
	/**
	 * Original signature : <code>float fluid_voice_gen_get(fluid_voice_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:55</i>
	 */
	float fluid_voice_gen_get(PointerByReference voice, int gen);
	/**
	 * Original signature : <code>void fluid_voice_gen_set(fluid_voice_t*, int, float)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:56</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_gen_set(com.sun.jna.ptr.PointerByReference, int, float)} instead
	 */
	@Deprecated 
	void fluid_voice_gen_set(Pointer voice, int gen, float val);
	/**
	 * Original signature : <code>void fluid_voice_gen_set(fluid_voice_t*, int, float)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:56</i>
	 */
	void fluid_voice_gen_set(PointerByReference voice, int gen, float val);
	/**
	 * Original signature : <code>void fluid_voice_gen_incr(fluid_voice_t*, int, float)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:57</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_gen_incr(com.sun.jna.ptr.PointerByReference, int, float)} instead
	 */
	@Deprecated 
	void fluid_voice_gen_incr(Pointer voice, int gen, float val);
	/**
	 * Original signature : <code>void fluid_voice_gen_incr(fluid_voice_t*, int, float)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:57</i>
	 */
	void fluid_voice_gen_incr(PointerByReference voice, int gen, float val);
	/**
	 * Original signature : <code>int fluid_voice_get_id(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:59</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_get_id(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_get_id(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_get_id(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:59</i>
	 */
	int fluid_voice_get_id(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_get_channel(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:60</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_get_channel(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_get_channel(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_get_channel(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:60</i>
	 */
	int fluid_voice_get_channel(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_get_key(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:61</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_get_key(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_get_key(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_get_key(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:61</i>
	 */
	int fluid_voice_get_key(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_get_actual_key(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:62</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_get_actual_key(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_get_actual_key(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_get_actual_key(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:62</i>
	 */
	int fluid_voice_get_actual_key(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_get_velocity(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:63</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_get_velocity(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_get_velocity(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_get_velocity(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:63</i>
	 */
	int fluid_voice_get_velocity(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_get_actual_velocity(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:64</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_get_actual_velocity(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_get_actual_velocity(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_get_actual_velocity(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:64</i>
	 */
	int fluid_voice_get_actual_velocity(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_is_playing(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:65</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_is_playing(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_is_playing(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_is_playing(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:65</i>
	 */
	int fluid_voice_is_playing(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_is_on(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:66</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_is_on(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_is_on(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_is_on(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:66</i>
	 */
	int fluid_voice_is_on(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_is_sustained(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:67</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_is_sustained(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_is_sustained(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_is_sustained(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:67</i>
	 */
	int fluid_voice_is_sustained(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_is_sostenuto(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:68</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_is_sostenuto(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_is_sostenuto(Pointer voice);
	/**
	 * Original signature : <code>int fluid_voice_is_sostenuto(const fluid_voice_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:68</i>
	 */
	int fluid_voice_is_sostenuto(PointerByReference voice);
	/**
	 * Original signature : <code>int fluid_voice_optimize_sample(fluid_sample_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:69</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_optimize_sample(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_voice_optimize_sample(Pointer s);
	/**
	 * Original signature : <code>int fluid_voice_optimize_sample(fluid_sample_t*)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:69</i>
	 */
	int fluid_voice_optimize_sample(PointerByReference s);
	/**
	 * Original signature : <code>void fluid_voice_update_param(fluid_voice_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:70</i><br>
	 * @deprecated use the safer method {@link #fluid_voice_update_param(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	void fluid_voice_update_param(Pointer voice, int gen);
	/**
	 * Original signature : <code>void fluid_voice_update_param(fluid_voice_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/voice.h:70</i>
	 */
	void fluid_voice_update_param(PointerByReference voice, int gen);
	public static class fluid_voice_t extends PointerType {
		public fluid_voice_t(Pointer address) {
			super(address);
		}
		public fluid_voice_t() {
			super();
		}
	};
	public static class fluid_sample_t extends PointerType {
		public fluid_sample_t(Pointer address) {
			super(address);
		}
		public fluid_sample_t() {
			super();
		}
	};
	public static class fluid_mod_t extends PointerType {
		public fluid_mod_t(Pointer address) {
			super(address);
		}
		public fluid_mod_t() {
			super();
		}
	};
}
