<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.tritonus</groupId>
    <artifactId>tritonus</artifactId>
    <version>0.3.13-SNAPSHOT</version>
  </parent>

  <artifactId>tritonus-fluidsynth</artifactId>
  <packaging>jar</packaging>

  <name>Tritonus fluidsynth Module</name>

  <profiles>
    <profile>
      <id>local (not on jitpack)</id>
      <activation>
        <property>
          <name>env.JITPACK</name>
          <value>!true</value>
        </property>
        <os>
          <family>mac</family>
        </os>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>1.0-alpha-11</version>
            <extensions>true</extensions>
            <configuration>
              <javahClassNames>
                <javahClassName>org.tritonus.midi.device.fluidsynth.FluidSynthesizer</javahClassName>
                <javahClassName>org.tritonus.midi.sb.fluidsynth.FluidSoundbank</javahClassName>
              </javahClassNames>
              <javahSearchJNIFromDependencies>false</javahSearchJNIFromDependencies>
              <javahOS>darwin</javahOS>
              <compilerProvider>generic-classic</compilerProvider>
              <compilerStartOptions>
                <compilerStartOption>-g -Wall -O2 -fomit-frame-pointer -fPIC</compilerStartOption>
                <!-- unless locating jdk includes, cause error why??? -->
                <compilerStartOption>-arch x86_64
                  -I${java.home}/../include
                  -I${java.home}/../include/darwin
                  -I /usr/local/include
                </compilerStartOption>
              </compilerStartOptions>
              <sources>
                <source>
                  <directory>src/main/native</directory>
                  <fileNames>
                    <fileName>org_tritonus_midi_device_fluidsynth_FluidSynthesizer.c</fileName>
                    <fileName>common/common.c</fileName>
                  </fileNames>
                </source>
              </sources>
              <linkerStartOptions>
                <linkerStartOption>-dynamiclib -arch x86_64
                  -L/usr/local/lib -lfluidsynth
                </linkerStartOption>
              </linkerStartOptions>
              <linkerFinalName/>
              <linkerEndOptions>
                <linkerEndOption>-o ${project.build.directory}/libtritonusfluid.dylib</linkerEndOption>
              </linkerEndOptions>
            </configuration>
            <executions>
              <execution>
                <id>compile-fluidsynth</id>
                <phase>compile</phase>
                <goals>
                  <goal>javah</goal>
                  <goal>compile</goal>
                  <goal>link</goal>
                </goals>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-install-plugin</artifactId>
            <version>3.0.0-M1</version>
            <executions>
              <execution>
                <id>install-library</id>
                <phase>install</phase>
                <goals>
                  <goal>install-file</goal>
                </goals>
                <configuration>
                  <groupId>${project.groupId}</groupId>
                  <artifactId>${project.artifactId}</artifactId>
                  <version>${project.parent.version}</version>
                  <packaging>dylib</packaging>
                  <file>${project.build.directory}/libtritonusfluid.dylib</file>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <!-- because of maven deploy-file uploads source, jar also -->
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>1.6.0</version>
            <executions>
              <execution>
                <id>deploy-library</id>
                <phase>deploy</phase>
                <goals>
                  <goal>exec</goal>
                </goals>
                <configuration>
                  <executable>mvn</executable>
                  <arguments>
                    <argument>deploy:deploy-file</argument>
                    <argument>-DgroupId=${project.groupId}</argument>
                    <argument>-DartifactId=${project.artifactId}</argument>
                    <argument>-Dversion=${project.parent.version}</argument>
                    <argument>-Dpackaging=dylib</argument>
                    <argument>-Dfile=${project.build.directory}/libtritonusfluid.dylib</argument>
                    <argument>-DgeneratePom=false</argument>
                    <argument>-DrepositoryId=github</argument>
                    <argument>-Durl=https://maven.pkg.github.com/umjammer/tritonus</argument>
                    <argument>-DgeneratePom=false</argument>
                    <argument>-s</argument>
                    <argument>${env.GITHUB_WORKSPACE}/settings.xml</argument>
                  </arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>local</id>
      <activation>
        <file>
          <exists>${basedir}/local.properties</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>properties-maven-plugin</artifactId>
            <version>1.0.0</version>
            <executions>
              <execution>
                <phase>initialize</phase>
                <goals>
                  <goal>read-project-properties</goal>
                </goals>
                <configuration>
                  <files>
                    <file>${basedir}/local.properties</file>
                  </files>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.10.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <encoding>utf-8</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M7</version>
        <configuration>
          <dependenciesToScan>
            <dependency>org.tritonus:tritonus-midishare</dependency>
          </dependenciesToScan>
          <forkMode>always</forkMode>
          <!-- mvn clean install -Dtritonus.fluidsynth.defaultsoundbank=your_soundfont_path -->
          <argLine>
            -Djava.util.logging.config.file=src/test/resources/logging.properties
            -Djava.library.path=${project.build.directory}:/usr/local/lib
          </argLine>
          <systemProperties>
            <tritonus.fluidsynth.defaultsoundbank>${tritonus.fluidsynth.defaultsoundbank}</tritonus.fluidsynth.defaultsoundbank>
          </systemProperties>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>org.tritonus</groupId>
      <artifactId>tritonus-share</artifactId>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-commons</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.tritonus</groupId>
      <artifactId>tritonus-share</artifactId>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.tritonus</groupId>
      <artifactId>tritonus-midishare</artifactId>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.github.umjammer</groupId>
      <artifactId>vavi-commons</artifactId>
      <version>1.1.8</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
