<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.tritonus</groupId>
  <artifactId>tritonus</artifactId>
  <version>0.3.13-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>Tritonus Parent Module</name>

  <modules>
    <module>tritonus-share</module>
    <module>tritonus-remaining</module>
    <module>tritonus-dsp</module>
    <module>tritonus-core</module>
    <module>tritonus-gsm</module>
    <module>tritonus-javasequencer</module>
    <module>tritonus-jorbis</module>
    <module>tritonus-midishare</module>
    <module>tritonus-mp3</module>
    <module>tritonus-esd</module>
    <module>tritonus-alsa</module>
    <module>tritonus-vorbis</module>
    <module>tritonus-pvorbis</module>
    <module>tritonus-cdda</module>
    <module>tritonus-fluidsynth</module>
    <module>tritonus-src</module>
    <module>tritonus-aos</module>
    <!--
        <module>tritonus-timidity</module>
    -->
    <module>tritonus-saol</module>
  </modules>

  <distributionManagement>
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/umjammer/tritonus</url>
    </repository>
  </distributionManagement>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.tritonus</groupId>
        <artifactId>tritonus-share</artifactId>
        <version>0.3.13-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.tritonus</groupId>
        <artifactId>tritonus-remaining</artifactId>
        <version>0.3.13-SNAPSHOT</version>
      </dependency>

      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>5.9.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.tritonus</groupId>
        <artifactId>tritonus-midishare</artifactId>
        <version>0.3.13-SNAPSHOT</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.tritonus</groupId>
        <artifactId>tritonus-share</artifactId>
        <version>0.3.13-SNAPSHOT</version>
        <type>test-jar</type>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.tritonus</groupId>
        <artifactId>tritonus-remaining</artifactId>
        <version>0.3.13-SNAPSHOT</version>
        <type>test-jar</type>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.tritonus</groupId>
        <artifactId>tritonus-midishare</artifactId>
        <version>0.3.13-SNAPSHOT</version>
        <type>test-jar</type>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>