package vavi.sound.sampled.jna.ogg;

import java.util.List;

import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;


/**
 * <i>native declaration : ogg/ogg.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ogg_iovec_t extends Structure {

    /** C type : void* */
    public Pointer iov_base;
    public NativeLong iov_len;

    public ogg_iovec_t() {
        super();
    }

    @Override
    protected List<String> getFieldOrder() {
        return List.of("iov_base", "iov_len");
    }

    /** @param iov_base C type : void* */
    public ogg_iovec_t(Pointer iov_base, NativeLong iov_len) {
        super();
        this.iov_base = iov_base;
        this.iov_len = iov_len;
    }

    public ogg_iovec_t(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends ogg_iovec_t implements Structure.ByReference {

    }

    public static class ByValue extends ogg_iovec_t implements Structure.ByValue {

    }

}
