package vavi.sound.midi.fluidsynth.jna.log;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;


/**
 * JNA Wrapper for library <b>log</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface LogLibrary extends Library {

    String JNA_LIBRARY_NAME = "fluidsynth";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(LogLibrary.JNA_LIBRARY_NAME);
    LogLibrary INSTANCE = Native.load(LogLibrary.JNA_LIBRARY_NAME, LogLibrary.class);

    /**
     * FluidSynth log levels.<br>
     * <i>native declaration : fluidsynth/log.h:61</i><br>
     * enum values
     */
    public static interface fluid_log_level {

        /**
         * < The synth can't function correctly any more<br>
         * <i>native declaration : fluidsynth/log.h:63</i>
         */
        int FLUID_PANIC = 0;
        /**
         * < Serious error occurred<br>
         * <i>native declaration : fluidsynth/log.h:64</i>
         */
        int FLUID_ERR = 1;
        /**
         * < Warning<br>
         * <i>native declaration : fluidsynth/log.h:65</i>
         */
        int FLUID_WARN = 2;
        /**
         * < Verbose informational messages<br>
         * <i>native declaration : fluidsynth/log.h:66</i>
         */
        int FLUID_INFO = 3;
        /**
         * < Debugging messages<br>
         * <i>native declaration : fluidsynth/log.h:67</i>
         */
        int FLUID_DBG = 4;
        /**
         * < @internal This symbol is not part of the public API and ABI<br>
         * stability guarantee and may change at any time!<br>
         * <i>native declaration : fluidsynth/log.h:68</i>
         */
        int LAST_LOG_LEVEL = 5;
    }

    ;

    /** <i>native declaration : fluidsynth/log.h</i> */
    public interface fluid_log_function_t extends Callback {

        void apply(int level, Pointer message, Pointer data);
    }

    ;

    /**
     * Original signature : <code>fluid_log_function_t fluid_set_log_function(int, fluid_log_function_t, void*)</code><br>
     * <i>native declaration : fluidsynth/log.h:82</i>
     */
    LogLibrary.fluid_log_function_t fluid_set_log_function(int level, LogLibrary.fluid_log_function_t fun, Pointer data);

    /**
     * Original signature : <code>void fluid_default_log_function(int, const char*, void*)</code><br>
     * <i>native declaration : fluidsynth/log.h:84</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_default_log_function(int, java.lang.String, com.sun.jna.Pointer)} and {@link #fluid_default_log_function(int, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    void fluid_default_log_function(int level, Pointer message, Pointer data);

    /**
     * Original signature : <code>void fluid_default_log_function(int, const char*, void*)</code><br>
     * <i>native declaration : fluidsynth/log.h:84</i>
     */
    void fluid_default_log_function(int level, String message, Pointer data);

    /**
     * Original signature : <code>int fluid_log(int, const char*, null)</code><br>
     * <i>native declaration : fluidsynth/log.h:86</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_log(int, java.lang.String, java.lang.Object)} and {@link #fluid_log(int, com.sun.jna.Pointer, java.lang.Object)} instead
     */
    @Deprecated
    int fluid_log(int level, Pointer fmt, Object... varArgs1);

    /**
     * Original signature : <code>int fluid_log(int, const char*, null)</code><br>
     * <i>native declaration : fluidsynth/log.h:86</i>
     */
    int fluid_log(int level, String fmt, Object... varArgs1);
}
