package vavi.sound.midi.fluidsynth.jna.sfont;

import java.nio.ByteBuffer;
import java.nio.ShortBuffer;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;
import com.sun.jna.ptr.ShortByReference;


/**
 * JNA Wrapper for library <b>sfont</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SfontLibrary extends Library {

    String JNA_LIBRARY_NAME = "fluidsynth";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SfontLibrary.JNA_LIBRARY_NAME);
    SfontLibrary INSTANCE = Native.load(SfontLibrary.JNA_LIBRARY_NAME, SfontLibrary.class);
    /** < Preset selected notify */
    int FLUID_PRESET_SELECTED = 0;
    /** < Preset unselected notify */
    int FLUID_PRESET_UNSELECTED = 1;
    /** < Sample no longer needed notify */
    int FLUID_SAMPLE_DONE = 2;
    /** < Request to pin preset samples to cache */
    int FLUID_PRESET_PIN = 3;
    /** < Request to unpin preset samples from cache */
    int FLUID_PRESET_UNPIN = 4;

    /**
     * Indicates the type of a sample used by the _fluid_sample_t::sampletype field.<br>
     * This enum corresponds to the \c SFSampleLink enum in the SoundFont spec.<br>
     * One \c flag may be bit-wise OR-ed with one \c value.<br>
     * <i>native declaration : include/fluidsynth/sfont.h:95</i><br>
     * enum values
     */
    interface fluid_sample_type {

        /**
         * < Value used for mono samples<br>
         * <i>native declaration : include/fluidsynth/sfont.h:97</i>
         */
        int FLUID_SAMPLETYPE_MONO = 0x1;
        /**
         * < Value used for right samples of a stereo pair<br>
         * <i>native declaration : include/fluidsynth/sfont.h:98</i>
         */
        int FLUID_SAMPLETYPE_RIGHT = 0x2;
        /**
         * < Value used for left samples of a stereo pair<br>
         * <i>native declaration : include/fluidsynth/sfont.h:99</i>
         */
        int FLUID_SAMPLETYPE_LEFT = 0x4;
        /**
         * < Value used for linked sample, which is currently not supported<br>
         * <i>native declaration : include/fluidsynth/sfont.h:100</i>
         */
        int FLUID_SAMPLETYPE_LINKED = 0x8;
        /**
         * < Flag used for Ogg Vorbis compressed samples (non-standard compliant extension) as found in the program "sftools" developed by Werner Schweer from MuseScore @since 1.1.7<br>
         * <i>native declaration : include/fluidsynth/sfont.h:101</i>
         */
        int FLUID_SAMPLETYPE_OGG_VORBIS = 0x10;
        /**
         * < Flag that indicates ROM samples, causing the sample to be ignored<br>
         * <i>native declaration : include/fluidsynth/sfont.h:102</i>
         */
        int FLUID_SAMPLETYPE_ROM = 0x8000;
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfloader_load_t extends Callback {

        PointerByReference apply(Pointer loader, Pointer filename);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfloader_free_t extends Callback {

        void apply(Pointer loader);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfloader_callback_open_t extends Callback {

        Pointer apply(Pointer filename);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfloader_callback_read_t extends Callback {

        int apply(Pointer buf, long count, Pointer handle);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfloader_callback_seek_t extends Callback {

        int apply(Pointer handle, long offset, int origin);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfloader_callback_close_t extends Callback {

        int apply(Pointer handle);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfloader_callback_tell_t extends Callback {

        long apply(Pointer handle);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfont_get_name_t extends Callback {

        String apply(Pointer sfont);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfont_get_preset_t extends Callback {

        PointerByReference apply(Pointer sfont, int bank, int prenum);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfont_iteration_start_t extends Callback {

        void apply(Pointer sfont);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfont_iteration_next_t extends Callback {

        PointerByReference apply(Pointer sfont);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_sfont_free_t extends Callback {

        int apply(Pointer sfont);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_preset_get_name_t extends Callback {

        String apply(Pointer preset);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_preset_get_banknum_t extends Callback {

        int apply(Pointer preset);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_preset_get_num_t extends Callback {

        int apply(Pointer preset);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_preset_noteon_t extends Callback {

        int apply(Pointer preset, Pointer synth, int chan, int key, int vel);
    }

    /** <i>native declaration : include/fluidsynth/sfont.h</i> */
    interface fluid_preset_free_t extends Callback {

        void apply(Pointer preset);
    }

    /**
     * @startlifecycle{SoundFont Loader}<br>
     * Original signature : <code>fluid_sfloader_t* new_fluid_sfloader(fluid_sfloader_load_t, fluid_sfloader_free_t)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:131</i>
     */
    PointerByReference new_fluid_sfloader(SfontLibrary.fluid_sfloader_load_t load, SfontLibrary.fluid_sfloader_free_t free);

    /**
     * Original signature : <code>void delete_fluid_sfloader(fluid_sfloader_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:132</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_sfloader(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void delete_fluid_sfloader(Pointer loader);

    /**
     * Original signature : <code>void delete_fluid_sfloader(fluid_sfloader_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:132</i>
     */
    void delete_fluid_sfloader(PointerByReference loader);

    /**
     * Original signature : <code>fluid_sfloader_t* new_fluid_defsfloader(fluid_settings_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:134</i><br>
     *
     * @deprecated use the safer method {@link #new_fluid_defsfloader(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    PointerByReference new_fluid_defsfloader(Pointer settings);

    /**
     * Original signature : <code>fluid_sfloader_t* new_fluid_defsfloader(fluid_settings_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:134</i>
     */
    PointerByReference new_fluid_defsfloader(PointerByReference settings);

    /**
     * Original signature : <code>int fluid_sfloader_set_callbacks(fluid_sfloader_t*, fluid_sfloader_callback_open_t, fluid_sfloader_callback_read_t, fluid_sfloader_callback_seek_t, fluid_sfloader_callback_tell_t, fluid_sfloader_callback_close_t)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:172</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfloader_set_callbacks(com.sun.jna.ptr.PointerByReference, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_sfloader_callback_open_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_sfloader_callback_read_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_sfloader_callback_seek_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_sfloader_callback_tell_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_sfloader_callback_close_t)} instead
     */
    @Deprecated
    int fluid_sfloader_set_callbacks(Pointer loader, SfontLibrary.fluid_sfloader_callback_open_t open, SfontLibrary.fluid_sfloader_callback_read_t read, SfontLibrary.fluid_sfloader_callback_seek_t seek, SfontLibrary.fluid_sfloader_callback_tell_t tell, SfontLibrary.fluid_sfloader_callback_close_t close);

    /**
     * Original signature : <code>int fluid_sfloader_set_callbacks(fluid_sfloader_t*, fluid_sfloader_callback_open_t, fluid_sfloader_callback_read_t, fluid_sfloader_callback_seek_t, fluid_sfloader_callback_tell_t, fluid_sfloader_callback_close_t)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:172</i>
     */
    int fluid_sfloader_set_callbacks(PointerByReference loader, SfontLibrary.fluid_sfloader_callback_open_t open, SfontLibrary.fluid_sfloader_callback_read_t read, SfontLibrary.fluid_sfloader_callback_seek_t seek, SfontLibrary.fluid_sfloader_callback_tell_t tell, SfontLibrary.fluid_sfloader_callback_close_t close);

    /**
     * Original signature : <code>int fluid_sfloader_set_data(fluid_sfloader_t*, void*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:179</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfloader_set_data(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_sfloader_set_data(Pointer loader, Pointer data);

    /**
     * Original signature : <code>int fluid_sfloader_set_data(fluid_sfloader_t*, void*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:179</i>
     */
    int fluid_sfloader_set_data(PointerByReference loader, Pointer data);

    /**
     * Original signature : <code>void* fluid_sfloader_get_data(fluid_sfloader_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:180</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfloader_get_data(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    Pointer fluid_sfloader_get_data(Pointer loader);

    /**
     * Original signature : <code>void* fluid_sfloader_get_data(fluid_sfloader_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:180</i>
     */
    Pointer fluid_sfloader_get_data(PointerByReference loader);

    /**
     * @startlifecycle{SoundFont}<br> Original signature : <code>fluid_sfont_t* new_fluid_sfont(fluid_sfont_get_name_t, fluid_sfont_get_preset_t, fluid_sfont_iteration_start_t, fluid_sfont_iteration_next_t, fluid_sfont_free_t)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:239</i>
     */
    PointerByReference new_fluid_sfont(SfontLibrary.fluid_sfont_get_name_t get_name, SfontLibrary.fluid_sfont_get_preset_t get_preset, SfontLibrary.fluid_sfont_iteration_start_t iter_start, SfontLibrary.fluid_sfont_iteration_next_t iter_next, SfontLibrary.fluid_sfont_free_t free);

    /**
     * Original signature : <code>int delete_fluid_sfont(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:245</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_sfont(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int delete_fluid_sfont(Pointer sfont);

    /**
     * Original signature : <code>int delete_fluid_sfont(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:245</i>
     */
    int delete_fluid_sfont(PointerByReference sfont);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_sfont_set_data(fluid_sfont_t*, void*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:248</i><br>
     * @deprecated use the safer method {@link #fluid_sfont_set_data(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_sfont_set_data(Pointer sfont, Pointer data);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_sfont_set_data(fluid_sfont_t*, void*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:248</i>
     */
    int fluid_sfont_set_data(PointerByReference sfont, Pointer data);

    /**
     * Original signature : <code>void* fluid_sfont_get_data(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:249</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfont_get_data(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    Pointer fluid_sfont_get_data(Pointer sfont);

    /**
     * Original signature : <code>void* fluid_sfont_get_data(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:249</i>
     */
    Pointer fluid_sfont_get_data(PointerByReference sfont);

    /**
     * Original signature : <code>int fluid_sfont_get_id(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:251</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfont_get_id(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_sfont_get_id(Pointer sfont);

    /**
     * Original signature : <code>int fluid_sfont_get_id(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:251</i>
     */
    int fluid_sfont_get_id(PointerByReference sfont);

    /**
     * Original signature : <code>char* fluid_sfont_get_name(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:252</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfont_get_name(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    String fluid_sfont_get_name(Pointer sfont);

    /**
     * Original signature : <code>char* fluid_sfont_get_name(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:252</i>
     */
    String fluid_sfont_get_name(PointerByReference sfont);

    /**
     * Original signature : <code>fluid_preset_t* fluid_sfont_get_preset(fluid_sfont_t*, int, int)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:253</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfont_get_preset(com.sun.jna.ptr.PointerByReference, int, int)} instead
     */
    @Deprecated
    PointerByReference fluid_sfont_get_preset(Pointer sfont, int bank, int prenum);

    /**
     * Original signature : <code>fluid_preset_t* fluid_sfont_get_preset(fluid_sfont_t*, int, int)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:253</i>
     */
    PointerByReference fluid_sfont_get_preset(PointerByReference sfont, int bank, int prenum);

    /**
     * Original signature : <code>void fluid_sfont_iteration_start(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:254</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfont_iteration_start(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void fluid_sfont_iteration_start(Pointer sfont);

    /**
     * Original signature : <code>void fluid_sfont_iteration_start(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:254</i>
     */
    void fluid_sfont_iteration_start(PointerByReference sfont);

    /**
     * Original signature : <code>fluid_preset_t* fluid_sfont_iteration_next(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:255</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sfont_iteration_next(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    PointerByReference fluid_sfont_iteration_next(Pointer sfont);

    /**
     * Original signature : <code>fluid_preset_t* fluid_sfont_iteration_next(fluid_sfont_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:255</i>
     */
    PointerByReference fluid_sfont_iteration_next(PointerByReference sfont);

    /**
     * @startlifecycle{Preset}<br> Original signature : <code>fluid_preset_t* new_fluid_preset(fluid_sfont_t*, fluid_preset_get_name_t, fluid_preset_get_banknum_t, fluid_preset_get_num_t, fluid_preset_noteon_t, fluid_preset_free_t)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:321</i><br>
     * @deprecated use the safer method {@link #new_fluid_preset(com.sun.jna.ptr.PointerByReference, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_preset_get_name_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_preset_get_banknum_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_preset_get_num_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_preset_noteon_t, vavi.sound.midi.fluidsynth.jna.sfont.SfontLibrary.fluid_preset_free_t)} instead
     */
    @Deprecated
    PointerByReference new_fluid_preset(Pointer parent_sfont, SfontLibrary.fluid_preset_get_name_t get_name, SfontLibrary.fluid_preset_get_banknum_t get_bank, SfontLibrary.fluid_preset_get_num_t get_num, SfontLibrary.fluid_preset_noteon_t noteon, SfontLibrary.fluid_preset_free_t free);

    /**
     * @startlifecycle{Preset}<br> Original signature : <code>fluid_preset_t* new_fluid_preset(fluid_sfont_t*, fluid_preset_get_name_t, fluid_preset_get_banknum_t, fluid_preset_get_num_t, fluid_preset_noteon_t, fluid_preset_free_t)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:321</i>
     */
    PointerByReference new_fluid_preset(PointerByReference parent_sfont, SfontLibrary.fluid_preset_get_name_t get_name, SfontLibrary.fluid_preset_get_banknum_t get_bank, SfontLibrary.fluid_preset_get_num_t get_num, SfontLibrary.fluid_preset_noteon_t noteon, SfontLibrary.fluid_preset_free_t free);

    /**
     * Original signature : <code>void delete_fluid_preset(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:327</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_preset(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void delete_fluid_preset(Pointer preset);

    /**
     * Original signature : <code>void delete_fluid_preset(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:327</i>
     */
    void delete_fluid_preset(PointerByReference preset);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_preset_set_data(fluid_preset_t*, void*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:330</i><br>
     * @deprecated use the safer method {@link #fluid_preset_set_data(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_preset_set_data(Pointer preset, Pointer data);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_preset_set_data(fluid_preset_t*, void*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:330</i>
     */
    int fluid_preset_set_data(PointerByReference preset, Pointer data);

    /**
     * Original signature : <code>void* fluid_preset_get_data(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:331</i><br>
     *
     * @deprecated use the safer method {@link #fluid_preset_get_data(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    Pointer fluid_preset_get_data(Pointer preset);

    /**
     * Original signature : <code>void* fluid_preset_get_data(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:331</i>
     */
    Pointer fluid_preset_get_data(PointerByReference preset);

    /**
     * Original signature : <code>char* fluid_preset_get_name(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:333</i><br>
     *
     * @deprecated use the safer method {@link #fluid_preset_get_name(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    String fluid_preset_get_name(Pointer preset);

    /**
     * Original signature : <code>char* fluid_preset_get_name(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:333</i>
     */
    String fluid_preset_get_name(PointerByReference preset);

    /**
     * Original signature : <code>int fluid_preset_get_banknum(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:334</i><br>
     *
     * @deprecated use the safer method {@link #fluid_preset_get_banknum(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_preset_get_banknum(Pointer preset);

    /**
     * Original signature : <code>int fluid_preset_get_banknum(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:334</i>
     */
    int fluid_preset_get_banknum(PointerByReference preset);

    /**
     * Original signature : <code>int fluid_preset_get_num(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:335</i><br>
     *
     * @deprecated use the safer method {@link #fluid_preset_get_num(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_preset_get_num(Pointer preset);

    /**
     * Original signature : <code>int fluid_preset_get_num(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:335</i>
     */
    int fluid_preset_get_num(PointerByReference preset);

    /**
     * Original signature : <code>fluid_sfont_t* fluid_preset_get_sfont(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:336</i><br>
     *
     * @deprecated use the safer method {@link #fluid_preset_get_sfont(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    PointerByReference fluid_preset_get_sfont(Pointer preset);

    /**
     * Original signature : <code>fluid_sfont_t* fluid_preset_get_sfont(fluid_preset_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:336</i>
     */
    PointerByReference fluid_preset_get_sfont(PointerByReference preset);

    /**
     * @startlifecycle{Sample}<br> Original signature : <code>fluid_sample_t* new_fluid_sample()</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:339</i>
     */
    PointerByReference new_fluid_sample();

    /**
     * Original signature : <code>void delete_fluid_sample(fluid_sample_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:340</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_sample(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void delete_fluid_sample(Pointer sample);

    /**
     * Original signature : <code>void delete_fluid_sample(fluid_sample_t*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:340</i>
     */
    void delete_fluid_sample(PointerByReference sample);

    /**
     * @endlifecycle<br> Original signature : <code>size_t fluid_sample_sizeof()</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:343</i>
     */
    NativeLong fluid_sample_sizeof();

    /**
     * Original signature : <code>int fluid_sample_set_name(fluid_sample_t*, const char*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:345</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_sample_set_name(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_sample_set_name(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_sample_set_name(Pointer sample, Pointer name);

    /**
     * Original signature : <code>int fluid_sample_set_name(fluid_sample_t*, const char*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:345</i>
     */
    int fluid_sample_set_name(PointerByReference sample, String name);

    /**
     * Original signature : <code>int fluid_sample_set_name(fluid_sample_t*, const char*)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:345</i>
     */
    int fluid_sample_set_name(PointerByReference sample, Pointer name);

    /**
     * Original signature : <code>int fluid_sample_set_sound_data(fluid_sample_t*, short*, char*, unsigned int, unsigned int, short)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:346</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_sample_set_sound_data(com.sun.jna.ptr.PointerByReference, java.nio.ShortBuffer, java.nio.ByteBuffer, int, int, short)} and {@link #fluid_sample_set_sound_data(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.ShortByReference, com.sun.jna.Pointer, int, int, short)} instead
     */
    @Deprecated
    int fluid_sample_set_sound_data(Pointer sample, ShortByReference data, Pointer data24, int nbframes, int sample_rate, short copy_data);

    /**
     * Original signature : <code>int fluid_sample_set_sound_data(fluid_sample_t*, short*, char*, unsigned int, unsigned int, short)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:346</i>
     */
    int fluid_sample_set_sound_data(PointerByReference sample, ShortBuffer data, ByteBuffer data24, int nbframes, int sample_rate, short copy_data);

    /**
     * Original signature : <code>int fluid_sample_set_sound_data(fluid_sample_t*, short*, char*, unsigned int, unsigned int, short)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:346</i>
     */
    int fluid_sample_set_sound_data(PointerByReference sample, ShortByReference data, Pointer data24, int nbframes, int sample_rate, short copy_data);

    /**
     * Original signature : <code>int fluid_sample_set_loop(fluid_sample_t*, unsigned int, unsigned int)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:353</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sample_set_loop(com.sun.jna.ptr.PointerByReference, int, int)} instead
     */
    @Deprecated
    int fluid_sample_set_loop(Pointer sample, int loop_start, int loop_end);

    /**
     * Original signature : <code>int fluid_sample_set_loop(fluid_sample_t*, unsigned int, unsigned int)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:353</i>
     */
    int fluid_sample_set_loop(PointerByReference sample, int loop_start, int loop_end);

    /**
     * Original signature : <code>int fluid_sample_set_pitch(fluid_sample_t*, int, int)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:354</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sample_set_pitch(com.sun.jna.ptr.PointerByReference, int, int)} instead
     */
    @Deprecated
    int fluid_sample_set_pitch(Pointer sample, int root_key, int fine_tune);

    /**
     * Original signature : <code>int fluid_sample_set_pitch(fluid_sample_t*, int, int)</code><br>
     * <i>native declaration : include/fluidsynth/sfont.h:354</i>
     */
    int fluid_sample_set_pitch(PointerByReference sample, int root_key, int fine_tune);

    class fluid_sfont_t extends PointerType {

        public fluid_sfont_t(Pointer address) {
            super(address);
        }

        public fluid_sfont_t() {
            super();
        }
    }

    class fluid_sfloader_t extends PointerType {

        public fluid_sfloader_t(Pointer address) {
            super(address);
        }

        public fluid_sfloader_t() {
            super();
        }
    }

    class fluid_preset_t extends PointerType {

        public fluid_preset_t(Pointer address) {
            super(address);
        }

        public fluid_preset_t() {
            super();
        }
    }

    class fluid_synth_t extends PointerType {

        public fluid_synth_t(Pointer address) {
            super(address);
        }

        public fluid_synth_t() {
            super();
        }
    }

}
