package vavi.sound.midi.fluidsynth.jna.midi;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>midi</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface MidiLibrary extends Library {
	String JNA_LIBRARY_NAME = "fluidsynth";
	NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(MidiLibrary.JNA_LIBRARY_NAME);
	MidiLibrary INSTANCE = Native.load(MidiLibrary.JNA_LIBRARY_NAME, MidiLibrary.class);
	/**
	 * <i>native declaration : fluidsynth/midi.h</i><br>
	 * enum values
	 */
	public static interface fluid_midi_router_rule_type {
		/** <i>native declaration : fluidsynth/midi.h:160</i> */
		int FLUID_MIDI_ROUTER_RULE_NOTE = 0;
		/** <i>native declaration : fluidsynth/midi.h:161</i> */
		int FLUID_MIDI_ROUTER_RULE_CC = 1;
		/** <i>native declaration : fluidsynth/midi.h:162</i> */
		int FLUID_MIDI_ROUTER_RULE_PROG_CHANGE = 2;
		/** <i>native declaration : fluidsynth/midi.h:163</i> */
		int FLUID_MIDI_ROUTER_RULE_PITCH_BEND = 3;
		/** <i>native declaration : fluidsynth/midi.h:164</i> */
		int FLUID_MIDI_ROUTER_RULE_CHANNEL_PRESSURE = 4;
		/** <i>native declaration : fluidsynth/midi.h:165</i> */
		int FLUID_MIDI_ROUTER_RULE_KEY_PRESSURE = 5;
		/**
		 * < @internal Total count of rule types. This symbol<br>
		 * is not part of the public API and ABI stability<br>
		 * guarantee and may change at any time!<br>
		 * <i>native declaration : fluidsynth/midi.h:166</i>
		 */
		int FLUID_MIDI_ROUTER_RULE_COUNT = 6;
	};
	/**
	 * MIDI File Player status enum.<br>
	 * @since 1.1.0<br>
	 * <i>native declaration : fluidsynth/midi.h:245</i><br>
	 * enum values
	 */
	public static interface fluid_player_status {
		/**
		 * < Player is ready<br>
		 * <i>native declaration : fluidsynth/midi.h:247</i>
		 */
		int FLUID_PLAYER_READY = 0;
		/**
		 * < Player is currently playing<br>
		 * <i>native declaration : fluidsynth/midi.h:248</i>
		 */
		int FLUID_PLAYER_PLAYING = 1;
		/**
		 * < Player is stopping, but hasn't finished yet (currently unused)<br>
		 * <i>native declaration : fluidsynth/midi.h:249</i>
		 */
		int FLUID_PLAYER_STOPPING = 2;
		/**
		 * < Player is finished playing<br>
		 * <i>native declaration : fluidsynth/midi.h:250</i>
		 */
		int FLUID_PLAYER_DONE = 3;
	};
	/**
	 * MIDI File Player tempo enum.<br>
	 * @since 2.2.0<br>
	 * <i>native declaration : fluidsynth/midi.h:257</i><br>
	 * enum values
	 */
	public static interface fluid_player_set_tempo_type {
		/**
		 * < Use midi file tempo set in midi file (120 bpm by default). Multiplied by a factor<br>
		 * <i>native declaration : fluidsynth/midi.h:259</i>
		 */
		int FLUID_PLAYER_TEMPO_INTERNAL = 0;
		/**
		 * < Set player tempo in bpm, supersede midi file tempo<br>
		 * <i>native declaration : fluidsynth/midi.h:260</i>
		 */
		int FLUID_PLAYER_TEMPO_EXTERNAL_BPM = 1;
		/**
		 * < Set player tempo in us per quarter note, supersede midi file tempo<br>
		 * <i>native declaration : fluidsynth/midi.h:261</i>
		 */
		int FLUID_PLAYER_TEMPO_EXTERNAL_MIDI = 2;
		/**
		 * < @internal Value defines the count of player tempo type (#fluid_player_set_tempo_type) @warning This symbol is not part of the public API and ABI stability guarantee and may change at any time!<br>
		 * <i>native declaration : fluidsynth/midi.h:262</i>
		 */
		int FLUID_PLAYER_TEMPO_NBR = 3;
	};
	/** <i>native declaration : fluidsynth/midi.h</i> */
	public interface handle_midi_event_func_t extends Callback {
		int apply(Pointer data, Pointer event);
	};
	/** <i>native declaration : fluidsynth/midi.h</i> */
	public interface handle_midi_tick_func_t extends Callback {
		int apply(Pointer data, int tick);
	};
	/**
	 * @startlifecycle{MIDI Event}<br>
	 * Original signature : <code>fluid_midi_event_t* new_fluid_midi_event()</code><br>
	 * <i>native declaration : fluidsynth/midi.h:112</i>
	 */
	PointerByReference new_fluid_midi_event();
	/**
	 * Original signature : <code>void delete_fluid_midi_event(fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:113</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_midi_event(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_midi_event(Pointer event);
	/**
	 * Original signature : <code>void delete_fluid_midi_event(fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:113</i>
	 */
	void delete_fluid_midi_event(PointerByReference event);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_midi_event_set_type(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:116</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_type(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_type(Pointer evt, int type);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_midi_event_set_type(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:116</i>
	 */
	int fluid_midi_event_set_type(PointerByReference evt, int type);
	/**
	 * Original signature : <code>int fluid_midi_event_get_type(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:117</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_type(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_type(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_type(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:117</i>
	 */
	int fluid_midi_event_get_type(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_set_channel(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:118</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_channel(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_channel(Pointer evt, int chan);
	/**
	 * Original signature : <code>int fluid_midi_event_set_channel(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:118</i>
	 */
	int fluid_midi_event_set_channel(PointerByReference evt, int chan);
	/**
	 * Original signature : <code>int fluid_midi_event_get_channel(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:119</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_channel(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_channel(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_channel(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:119</i>
	 */
	int fluid_midi_event_get_channel(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_key(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:120</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_key(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_key(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_key(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:120</i>
	 */
	int fluid_midi_event_get_key(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_set_key(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:121</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_key(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_key(Pointer evt, int key);
	/**
	 * Original signature : <code>int fluid_midi_event_set_key(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:121</i>
	 */
	int fluid_midi_event_set_key(PointerByReference evt, int key);
	/**
	 * Original signature : <code>int fluid_midi_event_get_velocity(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:122</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_velocity(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_velocity(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_velocity(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:122</i>
	 */
	int fluid_midi_event_get_velocity(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_set_velocity(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:123</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_velocity(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_velocity(Pointer evt, int vel);
	/**
	 * Original signature : <code>int fluid_midi_event_set_velocity(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:123</i>
	 */
	int fluid_midi_event_set_velocity(PointerByReference evt, int vel);
	/**
	 * Original signature : <code>int fluid_midi_event_get_control(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:124</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_control(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_control(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_control(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:124</i>
	 */
	int fluid_midi_event_get_control(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_set_control(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:125</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_control(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_control(Pointer evt, int ctrl);
	/**
	 * Original signature : <code>int fluid_midi_event_set_control(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:125</i>
	 */
	int fluid_midi_event_set_control(PointerByReference evt, int ctrl);
	/**
	 * Original signature : <code>int fluid_midi_event_get_value(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:126</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_value(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_value(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_value(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:126</i>
	 */
	int fluid_midi_event_get_value(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_set_value(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:127</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_value(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_value(Pointer evt, int val);
	/**
	 * Original signature : <code>int fluid_midi_event_set_value(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:127</i>
	 */
	int fluid_midi_event_set_value(PointerByReference evt, int val);
	/**
	 * Original signature : <code>int fluid_midi_event_get_program(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:128</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_program(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_program(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_program(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:128</i>
	 */
	int fluid_midi_event_get_program(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_set_program(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:129</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_program(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_program(Pointer evt, int val);
	/**
	 * Original signature : <code>int fluid_midi_event_set_program(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:129</i>
	 */
	int fluid_midi_event_set_program(PointerByReference evt, int val);
	/**
	 * Original signature : <code>int fluid_midi_event_get_pitch(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:130</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_get_pitch(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_pitch(Pointer evt);
	/**
	 * Original signature : <code>int fluid_midi_event_get_pitch(const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:130</i>
	 */
	int fluid_midi_event_get_pitch(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_midi_event_set_pitch(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:131</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_pitch(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_pitch(Pointer evt, int val);
	/**
	 * Original signature : <code>int fluid_midi_event_set_pitch(fluid_midi_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:131</i>
	 */
	int fluid_midi_event_set_pitch(PointerByReference evt, int val);
	/**
	 * Original signature : <code>int fluid_midi_event_set_sysex(fluid_midi_event_t*, void*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:132</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_sysex(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, int, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_sysex(Pointer evt, Pointer data, int size, int dynamic);
	/**
	 * Original signature : <code>int fluid_midi_event_set_sysex(fluid_midi_event_t*, void*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:132</i>
	 */
	int fluid_midi_event_set_sysex(PointerByReference evt, Pointer data, int size, int dynamic);
	/**
	 * Original signature : <code>int fluid_midi_event_set_text(fluid_midi_event_t*, void*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:134</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_text(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, int, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_text(Pointer evt, Pointer data, int size, int dynamic);
	/**
	 * Original signature : <code>int fluid_midi_event_set_text(fluid_midi_event_t*, void*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:134</i>
	 */
	int fluid_midi_event_set_text(PointerByReference evt, Pointer data, int size, int dynamic);
	/**
	 * Original signature : <code>int fluid_midi_event_get_text(fluid_midi_event_t*, void**, int*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:136</i><br>
	 * @deprecated use the safer methods {@link #fluid_midi_event_get_text(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, java.nio.IntBuffer)} and {@link #fluid_midi_event_get_text(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_text(Pointer evt, PointerByReference data, IntByReference size);
	/**
	 * Original signature : <code>int fluid_midi_event_get_text(fluid_midi_event_t*, void**, int*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:136</i>
	 */
	int fluid_midi_event_get_text(PointerByReference evt, PointerByReference data, IntBuffer size);
	/**
	 * Original signature : <code>int fluid_midi_event_get_text(fluid_midi_event_t*, void**, int*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:136</i>
	 */
	int fluid_midi_event_get_text(PointerByReference evt, PointerByReference data, IntByReference size);
	/**
	 * Original signature : <code>int fluid_midi_event_set_lyrics(fluid_midi_event_t*, void*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:138</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_event_set_lyrics(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, int, int)} instead
	 */
	@Deprecated 
	int fluid_midi_event_set_lyrics(Pointer evt, Pointer data, int size, int dynamic);
	/**
	 * Original signature : <code>int fluid_midi_event_set_lyrics(fluid_midi_event_t*, void*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:138</i>
	 */
	int fluid_midi_event_set_lyrics(PointerByReference evt, Pointer data, int size, int dynamic);
	/**
	 * Original signature : <code>int fluid_midi_event_get_lyrics(fluid_midi_event_t*, void**, int*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:140</i><br>
	 * @deprecated use the safer methods {@link #fluid_midi_event_get_lyrics(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, java.nio.IntBuffer)} and {@link #fluid_midi_event_get_lyrics(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_event_get_lyrics(Pointer evt, PointerByReference data, IntByReference size);
	/**
	 * Original signature : <code>int fluid_midi_event_get_lyrics(fluid_midi_event_t*, void**, int*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:140</i>
	 */
	int fluid_midi_event_get_lyrics(PointerByReference evt, PointerByReference data, IntBuffer size);
	/**
	 * Original signature : <code>int fluid_midi_event_get_lyrics(fluid_midi_event_t*, void**, int*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:140</i>
	 */
	int fluid_midi_event_get_lyrics(PointerByReference evt, PointerByReference data, IntByReference size);
	/**
	 * @startlifecycle{MIDI Router}<br>
	 * Original signature : <code>fluid_midi_router_t* new_fluid_midi_router(fluid_settings_t*, handle_midi_event_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:173</i><br>
	 * @deprecated use the safer method {@link #new_fluid_midi_router(com.sun.jna.ptr.PointerByReference, vavi.sound.midi.fluidsynth.jna.midi.MidiLibrary.handle_midi_event_func_t, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_midi_router(Pointer settings, MidiLibrary.handle_midi_event_func_t handler, Pointer event_handler_data);
	/**
	 * @startlifecycle{MIDI Router}<br>
	 * Original signature : <code>fluid_midi_router_t* new_fluid_midi_router(fluid_settings_t*, handle_midi_event_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:173</i>
	 */
	PointerByReference new_fluid_midi_router(PointerByReference settings, MidiLibrary.handle_midi_event_func_t handler, Pointer event_handler_data);
	/**
	 * Original signature : <code>void delete_fluid_midi_router(fluid_midi_router_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:176</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_midi_router(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_midi_router(Pointer handler);
	/**
	 * Original signature : <code>void delete_fluid_midi_router(fluid_midi_router_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:176</i>
	 */
	void delete_fluid_midi_router(PointerByReference handler);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_midi_router_set_default_rules(fluid_midi_router_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:179</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_router_set_default_rules(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_router_set_default_rules(Pointer router);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_midi_router_set_default_rules(fluid_midi_router_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:179</i>
	 */
	int fluid_midi_router_set_default_rules(PointerByReference router);
	/**
	 * Original signature : <code>int fluid_midi_router_clear_rules(fluid_midi_router_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:180</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_router_clear_rules(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_router_clear_rules(Pointer router);
	/**
	 * Original signature : <code>int fluid_midi_router_clear_rules(fluid_midi_router_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:180</i>
	 */
	int fluid_midi_router_clear_rules(PointerByReference router);
	/**
	 * Original signature : <code>int fluid_midi_router_add_rule(fluid_midi_router_t*, fluid_midi_router_rule_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:181</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_router_add_rule(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_midi_router_add_rule(Pointer router, Pointer rule, int type);
	/**
	 * Original signature : <code>int fluid_midi_router_add_rule(fluid_midi_router_t*, fluid_midi_router_rule_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:181</i>
	 */
	int fluid_midi_router_add_rule(PointerByReference router, PointerByReference rule, int type);
	/**
	 * @startlifecycle{MIDI Router Rule}<br>
	 * Original signature : <code>fluid_midi_router_rule_t* new_fluid_midi_router_rule()</code><br>
	 * <i>native declaration : fluidsynth/midi.h:186</i>
	 */
	PointerByReference new_fluid_midi_router_rule();
	/**
	 * Original signature : <code>void delete_fluid_midi_router_rule(fluid_midi_router_rule_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:187</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_midi_router_rule(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_midi_router_rule(Pointer rule);
	/**
	 * Original signature : <code>void delete_fluid_midi_router_rule(fluid_midi_router_rule_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:187</i>
	 */
	void delete_fluid_midi_router_rule(PointerByReference rule);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>void fluid_midi_router_rule_set_chan(fluid_midi_router_rule_t*, int, int, float, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:190</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_router_rule_set_chan(com.sun.jna.ptr.PointerByReference, int, int, float, int)} instead
	 */
	@Deprecated 
	void fluid_midi_router_rule_set_chan(Pointer rule, int min, int max, float mul, int add);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>void fluid_midi_router_rule_set_chan(fluid_midi_router_rule_t*, int, int, float, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:190</i>
	 */
	void fluid_midi_router_rule_set_chan(PointerByReference rule, int min, int max, float mul, int add);
	/**
	 * Original signature : <code>void fluid_midi_router_rule_set_param1(fluid_midi_router_rule_t*, int, int, float, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:192</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_router_rule_set_param1(com.sun.jna.ptr.PointerByReference, int, int, float, int)} instead
	 */
	@Deprecated 
	void fluid_midi_router_rule_set_param1(Pointer rule, int min, int max, float mul, int add);
	/**
	 * Original signature : <code>void fluid_midi_router_rule_set_param1(fluid_midi_router_rule_t*, int, int, float, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:192</i>
	 */
	void fluid_midi_router_rule_set_param1(PointerByReference rule, int min, int max, float mul, int add);
	/**
	 * Original signature : <code>void fluid_midi_router_rule_set_param2(fluid_midi_router_rule_t*, int, int, float, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:194</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_router_rule_set_param2(com.sun.jna.ptr.PointerByReference, int, int, float, int)} instead
	 */
	@Deprecated 
	void fluid_midi_router_rule_set_param2(Pointer rule, int min, int max, float mul, int add);
	/**
	 * Original signature : <code>void fluid_midi_router_rule_set_param2(fluid_midi_router_rule_t*, int, int, float, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:194</i>
	 */
	void fluid_midi_router_rule_set_param2(PointerByReference rule, int min, int max, float mul, int add);
	/**
	 * Original signature : <code>int fluid_midi_router_handle_midi_event(void*, fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:196</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_router_handle_midi_event(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_router_handle_midi_event(Pointer data, Pointer event);
	/**
	 * Original signature : <code>int fluid_midi_router_handle_midi_event(void*, fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:196</i>
	 */
	int fluid_midi_router_handle_midi_event(Pointer data, PointerByReference event);
	/**
	 * Original signature : <code>int fluid_midi_dump_prerouter(void*, fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:197</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_dump_prerouter(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_dump_prerouter(Pointer data, Pointer event);
	/**
	 * Original signature : <code>int fluid_midi_dump_prerouter(void*, fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:197</i>
	 */
	int fluid_midi_dump_prerouter(Pointer data, PointerByReference event);
	/**
	 * Original signature : <code>int fluid_midi_dump_postrouter(void*, fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:198</i><br>
	 * @deprecated use the safer method {@link #fluid_midi_dump_postrouter(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_midi_dump_postrouter(Pointer data, Pointer event);
	/**
	 * Original signature : <code>int fluid_midi_dump_postrouter(void*, fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:198</i>
	 */
	int fluid_midi_dump_postrouter(Pointer data, PointerByReference event);
	/**
	 * @startlifecycle{MIDI Driver}<br>
	 * Original signature : <code>fluid_midi_driver_t* new_fluid_midi_driver(fluid_settings_t*, handle_midi_event_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:223</i><br>
	 * @deprecated use the safer method {@link #new_fluid_midi_driver(com.sun.jna.ptr.PointerByReference, vavi.sound.midi.fluidsynth.jna.midi.MidiLibrary.handle_midi_event_func_t, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_midi_driver(Pointer settings, MidiLibrary.handle_midi_event_func_t handler, Pointer event_handler_data);
	/**
	 * @startlifecycle{MIDI Driver}<br>
	 * Original signature : <code>fluid_midi_driver_t* new_fluid_midi_driver(fluid_settings_t*, handle_midi_event_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:223</i>
	 */
	PointerByReference new_fluid_midi_driver(PointerByReference settings, MidiLibrary.handle_midi_event_func_t handler, Pointer event_handler_data);
	/**
	 * Original signature : <code>void delete_fluid_midi_driver(fluid_midi_driver_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:227</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_midi_driver(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_midi_driver(Pointer driver);
	/**
	 * Original signature : <code>void delete_fluid_midi_driver(fluid_midi_driver_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:227</i>
	 */
	void delete_fluid_midi_driver(PointerByReference driver);
	/**
	 * @startlifecycle{MIDI File Player}<br>
	 * Original signature : <code>fluid_player_t* new_fluid_player(fluid_synth_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:266</i><br>
	 * @deprecated use the safer method {@link #new_fluid_player(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_player(Pointer synth);
	/**
	 * @startlifecycle{MIDI File Player}<br>
	 * Original signature : <code>fluid_player_t* new_fluid_player(fluid_synth_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:266</i>
	 */
	PointerByReference new_fluid_player(PointerByReference synth);
	/**
	 * Original signature : <code>void delete_fluid_player(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:267</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_player(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_player(Pointer player);
	/**
	 * Original signature : <code>void delete_fluid_player(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:267</i>
	 */
	void delete_fluid_player(PointerByReference player);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_player_add(fluid_player_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:270</i><br>
	 * @deprecated use the safer methods {@link #fluid_player_add(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_player_add(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_player_add(Pointer player, Pointer midifile);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_player_add(fluid_player_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:270</i>
	 */
	int fluid_player_add(PointerByReference player, String midifile);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_player_add(fluid_player_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:270</i>
	 */
	int fluid_player_add(PointerByReference player, Pointer midifile);
	/**
	 * Original signature : <code>int fluid_player_add_mem(fluid_player_t*, const void*, size_t)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:271</i><br>
	 * @deprecated use the safer method {@link #fluid_player_add_mem(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.ochafik.lang.jnaerator.runtime.NativeLong)} instead
	 */
	@Deprecated 
	int fluid_player_add_mem(Pointer player, Pointer buffer, NativeLong len);
	/**
	 * Original signature : <code>int fluid_player_add_mem(fluid_player_t*, const void*, size_t)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:271</i>
	 */
	int fluid_player_add_mem(PointerByReference player, Pointer buffer, NativeLong len);
	/**
	 * Original signature : <code>int fluid_player_play(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:272</i><br>
	 * @deprecated use the safer method {@link #fluid_player_play(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_play(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_play(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:272</i>
	 */
	int fluid_player_play(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_stop(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:273</i><br>
	 * @deprecated use the safer method {@link #fluid_player_stop(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_stop(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_stop(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:273</i>
	 */
	int fluid_player_stop(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_join(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:274</i><br>
	 * @deprecated use the safer method {@link #fluid_player_join(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_join(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_join(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:274</i>
	 */
	int fluid_player_join(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_set_loop(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:275</i><br>
	 * @deprecated use the safer method {@link #fluid_player_set_loop(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_player_set_loop(Pointer player, int loop);
	/**
	 * Original signature : <code>int fluid_player_set_loop(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:275</i>
	 */
	int fluid_player_set_loop(PointerByReference player, int loop);
	/**
	 * Original signature : <code>int fluid_player_set_tempo(fluid_player_t*, int, double)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:276</i><br>
	 * @deprecated use the safer method {@link #fluid_player_set_tempo(com.sun.jna.ptr.PointerByReference, int, double)} instead
	 */
	@Deprecated 
	int fluid_player_set_tempo(Pointer player, int tempo_type, double tempo);
	/**
	 * Original signature : <code>int fluid_player_set_tempo(fluid_player_t*, int, double)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:276</i>
	 */
	int fluid_player_set_tempo(PointerByReference player, int tempo_type, double tempo);
	/**
	 * Original signature : <code>int fluid_player_set_midi_tempo(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:277</i><br>
	 * @deprecated use the safer method {@link #fluid_player_set_midi_tempo(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_player_set_midi_tempo(Pointer player, int tempo);
	/**
	 * Original signature : <code>int fluid_player_set_midi_tempo(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:277</i>
	 */
	int fluid_player_set_midi_tempo(PointerByReference player, int tempo);
	/**
	 * Original signature : <code>int fluid_player_set_bpm(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:278</i><br>
	 * @deprecated use the safer method {@link #fluid_player_set_bpm(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_player_set_bpm(Pointer player, int bpm);
	/**
	 * Original signature : <code>int fluid_player_set_bpm(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:278</i>
	 */
	int fluid_player_set_bpm(PointerByReference player, int bpm);
	/**
	 * Original signature : <code>int fluid_player_set_playback_callback(fluid_player_t*, handle_midi_event_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:279</i><br>
	 * @deprecated use the safer method {@link #fluid_player_set_playback_callback(com.sun.jna.ptr.PointerByReference, vavi.sound.midi.fluidsynth.jna.midi.MidiLibrary.handle_midi_event_func_t, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_player_set_playback_callback(Pointer player, MidiLibrary.handle_midi_event_func_t handler, Pointer handler_data);
	/**
	 * Original signature : <code>int fluid_player_set_playback_callback(fluid_player_t*, handle_midi_event_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:279</i>
	 */
	int fluid_player_set_playback_callback(PointerByReference player, MidiLibrary.handle_midi_event_func_t handler, Pointer handler_data);
	/**
	 * Original signature : <code>int fluid_player_set_tick_callback(fluid_player_t*, handle_midi_tick_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:280</i><br>
	 * @deprecated use the safer method {@link #fluid_player_set_tick_callback(com.sun.jna.ptr.PointerByReference, vavi.sound.midi.fluidsynth.jna.midi.MidiLibrary.handle_midi_tick_func_t, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_player_set_tick_callback(Pointer player, MidiLibrary.handle_midi_tick_func_t handler, Pointer handler_data);
	/**
	 * Original signature : <code>int fluid_player_set_tick_callback(fluid_player_t*, handle_midi_tick_func_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:280</i>
	 */
	int fluid_player_set_tick_callback(PointerByReference player, MidiLibrary.handle_midi_tick_func_t handler, Pointer handler_data);
	/**
	 * Original signature : <code>int fluid_player_get_status(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:282</i><br>
	 * @deprecated use the safer method {@link #fluid_player_get_status(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_get_status(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_get_status(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:282</i>
	 */
	int fluid_player_get_status(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_get_current_tick(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:283</i><br>
	 * @deprecated use the safer method {@link #fluid_player_get_current_tick(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_get_current_tick(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_get_current_tick(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:283</i>
	 */
	int fluid_player_get_current_tick(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_get_total_ticks(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:284</i><br>
	 * @deprecated use the safer method {@link #fluid_player_get_total_ticks(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_get_total_ticks(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_get_total_ticks(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:284</i>
	 */
	int fluid_player_get_total_ticks(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_get_bpm(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:285</i><br>
	 * @deprecated use the safer method {@link #fluid_player_get_bpm(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_get_bpm(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_get_bpm(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:285</i>
	 */
	int fluid_player_get_bpm(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_get_division(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:286</i><br>
	 * @deprecated use the safer method {@link #fluid_player_get_division(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_get_division(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_get_division(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:286</i>
	 */
	int fluid_player_get_division(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_get_midi_tempo(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:287</i><br>
	 * @deprecated use the safer method {@link #fluid_player_get_midi_tempo(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_player_get_midi_tempo(Pointer player);
	/**
	 * Original signature : <code>int fluid_player_get_midi_tempo(fluid_player_t*)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:287</i>
	 */
	int fluid_player_get_midi_tempo(PointerByReference player);
	/**
	 * Original signature : <code>int fluid_player_seek(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:288</i><br>
	 * @deprecated use the safer method {@link #fluid_player_seek(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	int fluid_player_seek(Pointer player, int ticks);
	/**
	 * Original signature : <code>int fluid_player_seek(fluid_player_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/midi.h:288</i>
	 */
	int fluid_player_seek(PointerByReference player, int ticks);
	public static class fluid_player_t extends PointerType {
		public fluid_player_t(Pointer address) {
			super(address);
		}
		public fluid_player_t() {
			super();
		}
	};
	public static class fluid_midi_driver_t extends PointerType {
		public fluid_midi_driver_t(Pointer address) {
			super(address);
		}
		public fluid_midi_driver_t() {
			super();
		}
	};
	public static class fluid_midi_router_rule_t extends PointerType {
		public fluid_midi_router_rule_t(Pointer address) {
			super(address);
		}
		public fluid_midi_router_rule_t() {
			super();
		}
	};
	public static class fluid_midi_router_t extends PointerType {
		public fluid_midi_router_t(Pointer address) {
			super(address);
		}
		public fluid_midi_router_t() {
			super();
		}
	};
}
