package vavi.sound.sampled.jna.vorbisfile;

import java.nio.ByteBuffer;
import java.nio.IntBuffer;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import vavi.sound.sampled.jna.codec.vorbis_comment;
import vavi.sound.sampled.jna.codec.vorbis_info;
import vavi.sound.sampled.jna.vorbisfile.ov_callbacks.ByValue;


/**
 * JNA Wrapper for library <b>vorbisfile</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface VorbisfileLibrary extends Library {

    String JNA_LIBRARY_NAME = "vorbisfile";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(VorbisfileLibrary.JNA_LIBRARY_NAME);
    VorbisfileLibrary INSTANCE = Native.load(VorbisfileLibrary.JNA_LIBRARY_NAME, VorbisfileLibrary.class);
    /** <i>native declaration : List<String>vorbis/vorbisfile.h</i> */
    int NOTOPEN = (int) 0;
    /** <i>native declaration : List<String>vorbis/vorbisfile.h</i> */
    int PARTOPEN = (int) 1;
    /** <i>native declaration : List<String>vorbis/vorbisfile.h</i> */
    int OPENED = (int) 2;
    /** <i>native declaration : List<String>vorbis/vorbisfile.h</i> */
    int STREAMSET = (int) 3;
    /** <i>native declaration : List<String>vorbis/vorbisfile.h</i> */
    int INITSET = (int) 4;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:73</i> */
    public interface OV_CALLBACKS_DEFAULT_expression_callback extends Callback {

        NativeLong apply(Pointer voidPtr1, NativeLong size_t1, NativeLong size_t2, Pointer voidPtr2);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:74</i> */
    public interface OV_CALLBACKS_DEFAULT_expression_callback2 extends Callback {

        int apply(Pointer voidPtr1, int int1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:75</i> */
    public interface OV_CALLBACKS_DEFAULT_expression_callback3 extends Callback {

        int apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:76</i> */
    public interface OV_CALLBACKS_DEFAULT_expression_callback4 extends Callback {

        NativeLong apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:80</i> */
    public interface OV_CALLBACKS_NOCLOSE_expression_callback extends Callback {

        NativeLong apply(Pointer voidPtr1, NativeLong size_t1, NativeLong size_t2, Pointer voidPtr2);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:81</i> */
    public interface OV_CALLBACKS_NOCLOSE_expression_callback2 extends Callback {

        int apply(Pointer voidPtr1, int int1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:82</i> */
    public interface OV_CALLBACKS_NOCLOSE_expression_callback3 extends Callback {

        int apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:83</i> */
    public interface OV_CALLBACKS_NOCLOSE_expression_callback4 extends Callback {

        NativeLong apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:87</i> */
    public interface OV_CALLBACKS_STREAMONLY_expression_callback extends Callback {

        NativeLong apply(Pointer voidPtr1, NativeLong size_t1, NativeLong size_t2, Pointer voidPtr2);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:88</i> */
    public interface OV_CALLBACKS_STREAMONLY_expression_callback2 extends Callback {

        int apply(Pointer voidPtr1, int int1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:89</i> */
    public interface OV_CALLBACKS_STREAMONLY_expression_callback3 extends Callback {

        int apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:90</i> */
    public interface OV_CALLBACKS_STREAMONLY_expression_callback4 extends Callback {

        NativeLong apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:94</i> */
    public interface OV_CALLBACKS_STREAMONLY_NOCLOSE_expression_callback extends Callback {

        NativeLong apply(Pointer voidPtr1, NativeLong size_t1, NativeLong size_t2, Pointer voidPtr2);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:95</i> */
    public interface OV_CALLBACKS_STREAMONLY_NOCLOSE_expression_callback2 extends Callback {

        int apply(Pointer voidPtr1, int int1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:96</i> */
    public interface OV_CALLBACKS_STREAMONLY_NOCLOSE_expression_callback3 extends Callback {

        int apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:97</i> */
    public interface OV_CALLBACKS_STREAMONLY_NOCLOSE_expression_callback4 extends Callback {

        NativeLong apply(Pointer voidPtr1);
    }

    ;

    /** <i>native declaration : List<String>vorbis/vorbisfile.h:190</i> */
    public interface ov_read_filter_filter_callback extends Callback {

        void apply(PointerByReference pcm, NativeLong channels, NativeLong samples, Pointer filter_param);
    }

    ;

    /**
     * a few sets of convenient callbacks, especially for use under<br>
     * Windows where ov_open_callbacks() should always be used instead of<br>
     * ov_open() to avoid problems with incompatible crt.o version linking<br>
     * issues.<br>
     * Original signature : <code>int _ov_header_fseek_wrap(FILE*, ogg_int64_t, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:50</i>
     */
    int _ov_header_fseek_wrap(VorbisfileLibrary.FILE f, long off, int whence);

    /**
     * Original signature : <code>int ov_clear(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:146</i>
     */
    int ov_clear(OggVorbis_File vf);

    /**
     * Original signature : <code>int ov_fopen(const char*, OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:147</i><br>
     *
     * @deprecated use the safer methods {@link #ov_fopen(java.lang.String, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File)} and {@link #ov_fopen(com.sun.jna.Pointer, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File)} instead
     */
    @Deprecated
    int ov_fopen(Pointer path, OggVorbis_File vf);

    /**
     * Original signature : <code>int ov_fopen(const char*, OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:147</i>
     */
    int ov_fopen(String path, OggVorbis_File vf);

    /**
     * Original signature : <code>int ov_open(FILE*, OggVorbis_File*, const char*, long)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:148</i><br>
     *
     * @deprecated use the safer methods {@link #ov_open(vavi.sound.sampled.jna.vorbisfile.VorbisfileLibrary.FILE, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, java.lang.String, com.sun.jna.NativeLong)} and {@link #ov_open(vavi.sound.sampled.jna.vorbisfile.VorbisfileLibrary.FILE, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.Pointer, com.sun.jna.NativeLong)} instead
     */
    @Deprecated
    int ov_open(VorbisfileLibrary.FILE f, OggVorbis_File vf, Pointer initial, NativeLong ibytes);

    /**
     * Original signature : <code>int ov_open(FILE*, OggVorbis_File*, const char*, long)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:148</i>
     */
    int ov_open(VorbisfileLibrary.FILE f, OggVorbis_File vf, String initial, NativeLong ibytes);

    /**
     * Original signature : <code>int ov_open_callbacks(void*, OggVorbis_File*, const char*, long, ov_callbacks)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:149</i><br>
     *
     * @deprecated use the safer methods {@link #ov_open_callbacks(com.sun.jna.Pointer, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, java.lang.String, com.sun.jna.NativeLong, vavi.sound.sampled.jna.vorbisfile.ov_callbacks.ByValue)} and {@link #ov_open_callbacks(com.sun.jna.Pointer, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.Pointer, com.sun.jna.NativeLong, vavi.sound.sampled.jna.vorbisfile.ov_callbacks.ByValue)} instead
     */
    @Deprecated
    int ov_open_callbacks(Pointer datasource, OggVorbis_File vf, Pointer initial, NativeLong ibytes, ByValue callbacks);

    /**
     * Original signature : <code>int ov_open_callbacks(void*, OggVorbis_File*, const char*, long, ov_callbacks)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:149</i>
     */
    int ov_open_callbacks(Pointer datasource, OggVorbis_File vf, String initial, NativeLong ibytes, ByValue callbacks);

    /**
     * Original signature : <code>int ov_test(FILE*, OggVorbis_File*, const char*, long)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:152</i><br>
     *
     * @deprecated use the safer methods {@link #ov_test(vavi.sound.sampled.jna.vorbisfile.VorbisfileLibrary.FILE, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, java.lang.String, com.sun.jna.NativeLong)} and {@link #ov_test(vavi.sound.sampled.jna.vorbisfile.VorbisfileLibrary.FILE, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.Pointer, com.sun.jna.NativeLong)} instead
     */
    @Deprecated
    int ov_test(VorbisfileLibrary.FILE f, OggVorbis_File vf, Pointer initial, NativeLong ibytes);

    /**
     * Original signature : <code>int ov_test(FILE*, OggVorbis_File*, const char*, long)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:152</i>
     */
    int ov_test(VorbisfileLibrary.FILE f, OggVorbis_File vf, String initial, NativeLong ibytes);

    /**
     * Original signature : <code>int ov_test_callbacks(void*, OggVorbis_File*, const char*, long, ov_callbacks)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:153</i><br>
     *
     * @deprecated use the safer methods {@link #ov_test_callbacks(com.sun.jna.Pointer, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, java.lang.String, com.sun.jna.NativeLong, vavi.sound.sampled.jna.vorbisfile.ov_callbacks.ByValue)} and {@link #ov_test_callbacks(com.sun.jna.Pointer, vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.Pointer, com.sun.jna.NativeLong, vavi.sound.sampled.jna.vorbisfile.ov_callbacks.ByValue)} instead
     */
    @Deprecated
    int ov_test_callbacks(Pointer datasource, OggVorbis_File vf, Pointer initial, NativeLong ibytes, ByValue callbacks);

    /**
     * Original signature : <code>int ov_test_callbacks(void*, OggVorbis_File*, const char*, long, ov_callbacks)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:153</i>
     */
    int ov_test_callbacks(Pointer datasource, OggVorbis_File vf, String initial, NativeLong ibytes, ByValue callbacks);

    /**
     * Original signature : <code>int ov_test_open(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:155</i>
     */
    int ov_test_open(OggVorbis_File vf);

    /**
     * Original signature : <code>long ov_bitrate(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:157</i>
     */
    NativeLong ov_bitrate(OggVorbis_File vf, int i);

    /**
     * Original signature : <code>long ov_bitrate_instant(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:158</i>
     */
    NativeLong ov_bitrate_instant(OggVorbis_File vf);

    /**
     * Original signature : <code>long ov_streams(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:159</i>
     */
    NativeLong ov_streams(OggVorbis_File vf);

    /**
     * Original signature : <code>long ov_seekable(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:160</i>
     */
    NativeLong ov_seekable(OggVorbis_File vf);

    /**
     * Original signature : <code>long ov_serialnumber(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:161</i>
     */
    NativeLong ov_serialnumber(OggVorbis_File vf, int i);

    /**
     * Original signature : <code>ogg_int64_t ov_raw_total(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:163</i>
     */
    long ov_raw_total(OggVorbis_File vf, int i);

    /**
     * Original signature : <code>ogg_int64_t ov_pcm_total(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:164</i>
     */
    long ov_pcm_total(OggVorbis_File vf, int i);

    /**
     * Original signature : <code>double ov_time_total(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:165</i>
     */
    double ov_time_total(OggVorbis_File vf, int i);

    /**
     * Original signature : <code>int ov_raw_seek(OggVorbis_File*, ogg_int64_t)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:167</i>
     */
    int ov_raw_seek(OggVorbis_File vf, long pos);

    /**
     * Original signature : <code>int ov_pcm_seek(OggVorbis_File*, ogg_int64_t)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:168</i>
     */
    int ov_pcm_seek(OggVorbis_File vf, long pos);

    /**
     * Original signature : <code>int ov_pcm_seek_page(OggVorbis_File*, ogg_int64_t)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:169</i>
     */
    int ov_pcm_seek_page(OggVorbis_File vf, long pos);

    /**
     * Original signature : <code>int ov_time_seek(OggVorbis_File*, double)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:170</i>
     */
    int ov_time_seek(OggVorbis_File vf, double pos);

    /**
     * Original signature : <code>int ov_time_seek_page(OggVorbis_File*, double)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:171</i>
     */
    int ov_time_seek_page(OggVorbis_File vf, double pos);

    /**
     * Original signature : <code>int ov_raw_seek_lap(OggVorbis_File*, ogg_int64_t)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:173</i>
     */
    int ov_raw_seek_lap(OggVorbis_File vf, long pos);

    /**
     * Original signature : <code>int ov_pcm_seek_lap(OggVorbis_File*, ogg_int64_t)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:174</i>
     */
    int ov_pcm_seek_lap(OggVorbis_File vf, long pos);

    /**
     * Original signature : <code>int ov_pcm_seek_page_lap(OggVorbis_File*, ogg_int64_t)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:175</i>
     */
    int ov_pcm_seek_page_lap(OggVorbis_File vf, long pos);

    /**
     * Original signature : <code>int ov_time_seek_lap(OggVorbis_File*, double)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:176</i>
     */
    int ov_time_seek_lap(OggVorbis_File vf, double pos);

    /**
     * Original signature : <code>int ov_time_seek_page_lap(OggVorbis_File*, double)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:177</i>
     */
    int ov_time_seek_page_lap(OggVorbis_File vf, double pos);

    /**
     * Original signature : <code>ogg_int64_t ov_raw_tell(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:179</i>
     */
    long ov_raw_tell(OggVorbis_File vf);

    /**
     * Original signature : <code>ogg_int64_t ov_pcm_tell(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:180</i>
     */
    long ov_pcm_tell(OggVorbis_File vf);

    /**
     * Original signature : <code>double ov_time_tell(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:181</i>
     */
    double ov_time_tell(OggVorbis_File vf);

    /**
     * Original signature : <code>vorbis_info* ov_info(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:183</i>
     */
    vorbis_info ov_info(OggVorbis_File vf, int link);

    /**
     * Original signature : <code>vorbis_comment* ov_comment(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:184</i>
     */
    vorbis_comment ov_comment(OggVorbis_File vf, int link);

    /**
     * Original signature : <code>long ov_read_float(OggVorbis_File*, float***, int, int*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:186</i><br>
     *
     * @deprecated use the safer methods {@link #ov_read_float(vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.ptr.PointerByReference, int, java.nio.IntBuffer)} and {@link #ov_read_float(vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.ptr.PointerByReference, int, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    NativeLong ov_read_float(OggVorbis_File vf, PointerByReference pcm_channels, int samples, IntByReference bitstream);

    /**
     * Original signature : <code>long ov_read_float(OggVorbis_File*, float***, int, int*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:186</i>
     */
    NativeLong ov_read_float(OggVorbis_File vf, PointerByReference pcm_channels, int samples, IntBuffer bitstream);

    /**
     * Original signature : <code>long ov_read_filter(OggVorbis_File*, char*, int, int, int, int, int*, ov_read_filter_filter_callback*, void*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:188</i><br>
     *
     * @deprecated use the safer methods {@link #ov_read_filter(vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, java.nio.ByteBuffer, int, int, int, int, java.nio.IntBuffer, vavi.sound.sampled.jna.vorbisfile.VorbisfileLibrary.ov_read_filter_filter_callback, com.sun.jna.Pointer)} and {@link #ov_read_filter(vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.Pointer, int, int, int, int, com.sun.jna.ptr.IntByReference, vavi.sound.sampled.jna.vorbisfile.VorbisfileLibrary.ov_read_filter_filter_callback, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    NativeLong ov_read_filter(OggVorbis_File vf, Pointer buffer, int length, int bigendianp, int word, int sgned, IntByReference bitstream, VorbisfileLibrary.ov_read_filter_filter_callback filter, Pointer filter_param);

    /**
     * Original signature : <code>long ov_read_filter(OggVorbis_File*, char*, int, int, int, int, int*, ov_read_filter_filter_callback*, void*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:188</i>
     */
    NativeLong ov_read_filter(OggVorbis_File vf, ByteBuffer buffer, int length, int bigendianp, int word, int sgned, IntBuffer bitstream, VorbisfileLibrary.ov_read_filter_filter_callback filter, Pointer filter_param);

    /**
     * Original signature : <code>long ov_read(OggVorbis_File*, char*, int, int, int, int, int*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:191</i><br>
     *
     * @deprecated use the safer methods {@link #ov_read(vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, java.nio.ByteBuffer, int, int, int, int, java.nio.IntBuffer)} and {@link #ov_read(vavi.sound.sampled.jna.vorbisfile.OggVorbis_File, com.sun.jna.Pointer, int, int, int, int, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    NativeLong ov_read(OggVorbis_File vf, Pointer buffer, int length, int bigendianp, int word, int sgned, IntByReference bitstream);

    /**
     * Original signature : <code>long ov_read(OggVorbis_File*, char*, int, int, int, int, int*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:191</i>
     */
    NativeLong ov_read(OggVorbis_File vf, ByteBuffer buffer, int length, int bigendianp, int word, int sgned, IntBuffer bitstream);

    /**
     * Original signature : <code>int ov_crosslap(OggVorbis_File*, OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:193</i>
     */
    int ov_crosslap(OggVorbis_File vf1, OggVorbis_File vf2);

    /**
     * Original signature : <code>int ov_halfrate(OggVorbis_File*, int)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:195</i>
     */
    int ov_halfrate(OggVorbis_File vf, int flag);

    /**
     * Original signature : <code>int ov_halfrate_p(OggVorbis_File*)</code><br>
     * <i>native declaration : List<String>vorbis/vorbisfile.h:196</i>
     */
    int ov_halfrate_p(OggVorbis_File vf);

    public static class FILE extends PointerType {

        public FILE(Pointer address) {
            super(address);
        }

        public FILE() {
            super();
        }
    }

    ;
}
