package vavi.sound.midi.fluidsynth.jna.audio;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;


/**
 * JNA Wrapper for library <b>audio</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface AudioLibrary extends Library {

    String JNA_LIBRARY_NAME = "fluidsynth";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(AudioLibrary.JNA_LIBRARY_NAME);
    AudioLibrary INSTANCE = Native.load(AudioLibrary.JNA_LIBRARY_NAME, AudioLibrary.class);

    /** <i>native declaration : fluidsynth/audio.h</i> */
    public interface fluid_audio_func_t extends Callback {

        int apply(Pointer data, int len, int nfx, PointerByReference fx, int nout, PointerByReference out);
    }

    ;

    /**
     * @startlifecycle{Audio Driver}<br>
     * Original signature : <code>fluid_audio_driver_t* new_fluid_audio_driver(fluid_settings_t*, fluid_synth_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:112</i><br>
     * @deprecated use the safer method {@link #new_fluid_audio_driver(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    PointerByReference new_fluid_audio_driver(Pointer settings, Pointer synth);

    /**
     * @startlifecycle{Audio Driver}<br>
     * Original signature : <code>fluid_audio_driver_t* new_fluid_audio_driver(fluid_settings_t*, fluid_synth_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:112</i>
     */
    PointerByReference new_fluid_audio_driver(PointerByReference settings, PointerByReference synth);

    /**
     * Original signature : <code>fluid_audio_driver_t* new_fluid_audio_driver2(fluid_settings_t*, fluid_audio_func_t, void*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:115</i><br>
     *
     * @deprecated use the safer method {@link #new_fluid_audio_driver2(com.sun.jna.ptr.PointerByReference, vavi.sound.midi.fluidsynth.jna.audio.AudioLibrary.fluid_audio_func_t, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    PointerByReference new_fluid_audio_driver2(Pointer settings, AudioLibrary.fluid_audio_func_t func, Pointer data);

    /**
     * Original signature : <code>fluid_audio_driver_t* new_fluid_audio_driver2(fluid_settings_t*, fluid_audio_func_t, void*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:115</i>
     */
    PointerByReference new_fluid_audio_driver2(PointerByReference settings, AudioLibrary.fluid_audio_func_t func, Pointer data);

    /**
     * Original signature : <code>void delete_fluid_audio_driver(fluid_audio_driver_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:119</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_audio_driver(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void delete_fluid_audio_driver(Pointer driver);

    /**
     * Original signature : <code>void delete_fluid_audio_driver(fluid_audio_driver_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:119</i>
     */
    void delete_fluid_audio_driver(PointerByReference driver);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_audio_driver_register(const char**)</code><br>
     * <i>native declaration : fluidsynth/audio.h:122</i><br>
     * @deprecated use the safer methods {@link #fluid_audio_driver_register(java.lang.String[])} and {@link #fluid_audio_driver_register(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_audio_driver_register(PointerByReference adrivers);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_audio_driver_register(const char**)</code><br>
     * <i>native declaration : fluidsynth/audio.h:122</i>
     */
    int fluid_audio_driver_register(String adrivers[]);

    /**
     * @startlifecycle{File Renderer}<br>
     * Original signature : <code>fluid_file_renderer_t* new_fluid_file_renderer(fluid_synth_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:143</i><br>
     * @deprecated use the safer method {@link #new_fluid_file_renderer(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    PointerByReference new_fluid_file_renderer(Pointer synth);

    /**
     * @startlifecycle{File Renderer}<br>
     * Original signature : <code>fluid_file_renderer_t* new_fluid_file_renderer(fluid_synth_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:143</i>
     */
    PointerByReference new_fluid_file_renderer(PointerByReference synth);

    /**
     * Original signature : <code>void delete_fluid_file_renderer(fluid_file_renderer_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:144</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_file_renderer(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void delete_fluid_file_renderer(Pointer dev);

    /**
     * Original signature : <code>void delete_fluid_file_renderer(fluid_file_renderer_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:144</i>
     */
    void delete_fluid_file_renderer(PointerByReference dev);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_file_renderer_process_block(fluid_file_renderer_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:147</i><br>
     * @deprecated use the safer method {@link #fluid_file_renderer_process_block(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_file_renderer_process_block(Pointer dev);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_file_renderer_process_block(fluid_file_renderer_t*)</code><br>
     * <i>native declaration : fluidsynth/audio.h:147</i>
     */
    int fluid_file_renderer_process_block(PointerByReference dev);

    /**
     * Original signature : <code>int fluid_file_set_encoding_quality(fluid_file_renderer_t*, double)</code><br>
     * <i>native declaration : fluidsynth/audio.h:148</i><br>
     *
     * @deprecated use the safer method {@link #fluid_file_set_encoding_quality(com.sun.jna.ptr.PointerByReference, double)} instead
     */
    @Deprecated
    int fluid_file_set_encoding_quality(Pointer dev, double q);

    /**
     * Original signature : <code>int fluid_file_set_encoding_quality(fluid_file_renderer_t*, double)</code><br>
     * <i>native declaration : fluidsynth/audio.h:148</i>
     */
    int fluid_file_set_encoding_quality(PointerByReference dev, double q);

    public static class fluid_audio_driver_t extends PointerType {

        public fluid_audio_driver_t(Pointer address) {
            super(address);
        }

        public fluid_audio_driver_t() {
            super();
        }
    }

    ;

    public static class fluid_file_renderer_t extends PointerType {

        public fluid_file_renderer_t(Pointer address) {
            super(address);
        }

        public fluid_file_renderer_t() {
            super();
        }
    }

    ;
}
