package vavi.sound.midi.fluidsynth.jna.settings;

import java.nio.ByteBuffer;
import java.nio.DoubleBuffer;
import java.nio.IntBuffer;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;


/**
 * JNA Wrapper for library <b>settings</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SettingsLibrary extends Library {

    String JNA_LIBRARY_NAME = "fluidsynth";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SettingsLibrary.JNA_LIBRARY_NAME);
    SettingsLibrary INSTANCE = Native.load(SettingsLibrary.JNA_LIBRARY_NAME, SettingsLibrary.class);

    /**
     * Settings type<br>
     * Each setting has a defined type: numeric (double), integer, string or a<br>
     * set of values. The type of each setting can be retrieved using the<br>
     * function fluid_settings_get_type()<br>
     * <i>native declaration : fluidsynth/settings.h:93</i><br>
     * enum values
     */
    interface fluid_types_enum {

        /**
         * < Undefined type<br>
         * <i>native declaration : fluidsynth/settings.h:95</i>
         */
        int FLUID_NO_TYPE = -1;
        /**
         * < Numeric (double)<br>
         * <i>native declaration : fluidsynth/settings.h:96</i>
         */
        int FLUID_NUM_TYPE = 0;
        /**
         * < Integer<br>
         * <i>native declaration : fluidsynth/settings.h:97</i>
         */
        int FLUID_INT_TYPE = 1;
        /**
         * < String<br>
         * <i>native declaration : fluidsynth/settings.h:98</i>
         */
        int FLUID_STR_TYPE = 2;
        /**
         * < Set of values<br>
         * <i>native declaration : fluidsynth/settings.h:99</i>
         */
        int FLUID_SET_TYPE = 3;
    }

    ;
    /** <i>native declaration : fluidsynth/settings.h</i> */
    int FLUID_HINT_BOUNDED_BELOW = (int) 0x1;
    /** <i>native declaration : fluidsynth/settings.h</i> */
    int FLUID_HINT_BOUNDED_ABOVE = (int) 0x2;
    /** <i>native declaration : fluidsynth/settings.h</i> */
    int FLUID_HINT_TOGGLED = (int) 0x4;
    /** <i>native declaration : fluidsynth/settings.h</i> */
    int FLUID_HINT_OPTIONLIST = (int) 0x02;

    /** <i>native declaration : fluidsynth/settings.h</i> */
    public interface fluid_settings_foreach_option_t extends Callback {

        void apply(Pointer data, Pointer name, Pointer option);
    }

    ;

    /** <i>native declaration : fluidsynth/settings.h</i> */
    public interface fluid_settings_foreach_t extends Callback {

        void apply(Pointer data, Pointer name, int type);
    }

    ;

    /**
     * @startlifecycle{Settings}<br> Original signature : <code>fluid_settings_t* new_fluid_settings()</code><br>
     * <i>native declaration : fluidsynth/settings.h:103</i>
     */
    PointerByReference new_fluid_settings();

    /**
     * Original signature : <code>void delete_fluid_settings(fluid_settings_t*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:104</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_settings(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void delete_fluid_settings(Pointer settings);

    /**
     * Original signature : <code>void delete_fluid_settings(fluid_settings_t*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:104</i>
     */
    void delete_fluid_settings(PointerByReference settings);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_settings_get_type(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:108</i><br>
     * @deprecated use the safer methods {@link #fluid_settings_get_type(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_settings_get_type(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_settings_get_type(Pointer settings, Pointer name);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_settings_get_type(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:108</i>
     */
    int fluid_settings_get_type(PointerByReference settings, String name);

    /**
     * @endlifecycle<br> Original signature : <code>int fluid_settings_get_type(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:108</i>
     */
    int fluid_settings_get_type(PointerByReference settings, Pointer name);

    /**
     * Original signature : <code>int fluid_settings_get_hints(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:111</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_get_hints(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.IntBuffer)} and {@link #fluid_settings_get_hints(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    int fluid_settings_get_hints(Pointer settings, Pointer name, IntByReference val);

    /**
     * Original signature : <code>int fluid_settings_get_hints(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:111</i>
     */
    int fluid_settings_get_hints(PointerByReference settings, String name, IntBuffer val);

    /**
     * Original signature : <code>int fluid_settings_get_hints(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:111</i>
     */
    int fluid_settings_get_hints(PointerByReference settings, Pointer name, IntByReference val);

    /**
     * Original signature : <code>int fluid_settings_is_realtime(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:114</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_is_realtime(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_settings_is_realtime(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_settings_is_realtime(Pointer settings, Pointer name);

    /**
     * Original signature : <code>int fluid_settings_is_realtime(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:114</i>
     */
    int fluid_settings_is_realtime(PointerByReference settings, String name);

    /**
     * Original signature : <code>int fluid_settings_is_realtime(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:114</i>
     */
    int fluid_settings_is_realtime(PointerByReference settings, Pointer name);

    /**
     * Original signature : <code>int fluid_settings_setstr(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:117</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_setstr(com.sun.jna.ptr.PointerByReference, java.lang.String, java.lang.String)} and {@link #fluid_settings_setstr(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_settings_setstr(Pointer settings, Pointer name, Pointer str);

    /**
     * Original signature : <code>int fluid_settings_setstr(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:117</i>
     */
    int fluid_settings_setstr(PointerByReference settings, String name, String str);

    /**
     * Original signature : <code>int fluid_settings_setstr(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:117</i>
     */
    int fluid_settings_setstr(PointerByReference settings, Pointer name, Pointer str);

    /**
     * Original signature : <code>int fluid_settings_copystr(fluid_settings_t*, const char*, char*, int)</code><br>
     * <i>native declaration : fluidsynth/settings.h:120</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_copystr(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.ByteBuffer, int)} and {@link #fluid_settings_copystr(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int fluid_settings_copystr(Pointer settings, Pointer name, Pointer str, int len);

    /**
     * Original signature : <code>int fluid_settings_copystr(fluid_settings_t*, const char*, char*, int)</code><br>
     * <i>native declaration : fluidsynth/settings.h:120</i>
     */
    int fluid_settings_copystr(PointerByReference settings, String name, ByteBuffer str, int len);

    /**
     * Original signature : <code>int fluid_settings_copystr(fluid_settings_t*, const char*, char*, int)</code><br>
     * <i>native declaration : fluidsynth/settings.h:120</i>
     */
    int fluid_settings_copystr(PointerByReference settings, Pointer name, Pointer str, int len);

    /**
     * Original signature : <code>int fluid_settings_dupstr(fluid_settings_t*, const char*, char**)</code><br>
     * <i>native declaration : fluidsynth/settings.h:123</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_dupstr(com.sun.jna.ptr.PointerByReference, java.lang.String, com.sun.jna.ptr.PointerByReference)} and {@link #fluid_settings_dupstr(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_settings_dupstr(Pointer settings, Pointer name, PointerByReference str);

    /**
     * Original signature : <code>int fluid_settings_dupstr(fluid_settings_t*, const char*, char**)</code><br>
     * <i>native declaration : fluidsynth/settings.h:123</i>
     */
    int fluid_settings_dupstr(PointerByReference settings, String name, PointerByReference str);

    /**
     * Original signature : <code>int fluid_settings_dupstr(fluid_settings_t*, const char*, char**)</code><br>
     * <i>native declaration : fluidsynth/settings.h:123</i>
     */
    int fluid_settings_dupstr(PointerByReference settings, Pointer name, PointerByReference str);

    /**
     * Original signature : <code>int fluid_settings_getstr_default(fluid_settings_t*, const char*, char**)</code><br>
     * <i>native declaration : fluidsynth/settings.h:126</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_getstr_default(com.sun.jna.ptr.PointerByReference, java.lang.String, com.sun.jna.ptr.PointerByReference)} and {@link #fluid_settings_getstr_default(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_settings_getstr_default(Pointer settings, Pointer name, PointerByReference def);

    /**
     * Original signature : <code>int fluid_settings_getstr_default(fluid_settings_t*, const char*, char**)</code><br>
     * <i>native declaration : fluidsynth/settings.h:126</i>
     */
    int fluid_settings_getstr_default(PointerByReference settings, String name, PointerByReference def);

    /**
     * Original signature : <code>int fluid_settings_getstr_default(fluid_settings_t*, const char*, char**)</code><br>
     * <i>native declaration : fluidsynth/settings.h:126</i>
     */
    int fluid_settings_getstr_default(PointerByReference settings, Pointer name, PointerByReference def);

    /**
     * Original signature : <code>int fluid_settings_str_equal(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:129</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_str_equal(com.sun.jna.ptr.PointerByReference, java.lang.String, java.lang.String)} and {@link #fluid_settings_str_equal(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_settings_str_equal(Pointer settings, Pointer name, Pointer value);

    /**
     * Original signature : <code>int fluid_settings_str_equal(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:129</i>
     */
    int fluid_settings_str_equal(PointerByReference settings, String name, String value);

    /**
     * Original signature : <code>int fluid_settings_str_equal(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:129</i>
     */
    int fluid_settings_str_equal(PointerByReference settings, Pointer name, Pointer value);

    /**
     * Original signature : <code>int fluid_settings_setnum(fluid_settings_t*, const char*, double)</code><br>
     * <i>native declaration : fluidsynth/settings.h:132</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_setnum(com.sun.jna.ptr.PointerByReference, java.lang.String, double)} and {@link #fluid_settings_setnum(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, double)} instead
     */
    @Deprecated
    int fluid_settings_setnum(Pointer settings, Pointer name, double val);

    /**
     * Original signature : <code>int fluid_settings_setnum(fluid_settings_t*, const char*, double)</code><br>
     * <i>native declaration : fluidsynth/settings.h:132</i>
     */
    int fluid_settings_setnum(PointerByReference settings, String name, double val);

    /**
     * Original signature : <code>int fluid_settings_setnum(fluid_settings_t*, const char*, double)</code><br>
     * <i>native declaration : fluidsynth/settings.h:132</i>
     */
    int fluid_settings_setnum(PointerByReference settings, Pointer name, double val);

    /**
     * Original signature : <code>int fluid_settings_getnum(fluid_settings_t*, const char*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:135</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_getnum(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.DoubleBuffer)} and {@link #fluid_settings_getnum(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
     */
    @Deprecated
    int fluid_settings_getnum(Pointer settings, Pointer name, DoubleByReference val);

    /**
     * Original signature : <code>int fluid_settings_getnum(fluid_settings_t*, const char*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:135</i>
     */
    int fluid_settings_getnum(PointerByReference settings, String name, DoubleBuffer val);

    /**
     * Original signature : <code>int fluid_settings_getnum(fluid_settings_t*, const char*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:135</i>
     */
    int fluid_settings_getnum(PointerByReference settings, Pointer name, DoubleByReference val);

    /**
     * Original signature : <code>int fluid_settings_getnum_default(fluid_settings_t*, const char*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:138</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_getnum_default(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.DoubleBuffer)} and {@link #fluid_settings_getnum_default(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
     */
    @Deprecated
    int fluid_settings_getnum_default(Pointer settings, Pointer name, DoubleByReference val);

    /**
     * Original signature : <code>int fluid_settings_getnum_default(fluid_settings_t*, const char*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:138</i>
     */
    int fluid_settings_getnum_default(PointerByReference settings, String name, DoubleBuffer val);

    /**
     * Original signature : <code>int fluid_settings_getnum_default(fluid_settings_t*, const char*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:138</i>
     */
    int fluid_settings_getnum_default(PointerByReference settings, Pointer name, DoubleByReference val);

    /**
     * Original signature : <code>int fluid_settings_getnum_range(fluid_settings_t*, const char*, double*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:141</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_getnum_range(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.DoubleBuffer, java.nio.DoubleBuffer)} and {@link #fluid_settings_getnum_range(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.DoubleByReference)} instead
     */
    @Deprecated
    int fluid_settings_getnum_range(Pointer settings, Pointer name, DoubleByReference min, DoubleByReference max);

    /**
     * Original signature : <code>int fluid_settings_getnum_range(fluid_settings_t*, const char*, double*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:141</i>
     */
    int fluid_settings_getnum_range(PointerByReference settings, String name, DoubleBuffer min, DoubleBuffer max);

    /**
     * Original signature : <code>int fluid_settings_getnum_range(fluid_settings_t*, const char*, double*, double*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:141</i>
     */
    int fluid_settings_getnum_range(PointerByReference settings, Pointer name, DoubleByReference min, DoubleByReference max);

    /**
     * Original signature : <code>int fluid_settings_setint(fluid_settings_t*, const char*, int)</code><br>
     * <i>native declaration : fluidsynth/settings.h:145</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_setint(com.sun.jna.ptr.PointerByReference, java.lang.String, int)} and {@link #fluid_settings_setint(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int fluid_settings_setint(Pointer settings, Pointer name, int val);

    /**
     * Original signature : <code>int fluid_settings_setint(fluid_settings_t*, const char*, int)</code><br>
     * <i>native declaration : fluidsynth/settings.h:145</i>
     */
    int fluid_settings_setint(PointerByReference settings, String name, int val);

    /**
     * Original signature : <code>int fluid_settings_setint(fluid_settings_t*, const char*, int)</code><br>
     * <i>native declaration : fluidsynth/settings.h:145</i>
     */
    int fluid_settings_setint(PointerByReference settings, Pointer name, int val);

    /**
     * Original signature : <code>int fluid_settings_getint(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:148</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_getint(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.IntBuffer)} and {@link #fluid_settings_getint(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    int fluid_settings_getint(Pointer settings, Pointer name, IntByReference val);

    /**
     * Original signature : <code>int fluid_settings_getint(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:148</i>
     */
    int fluid_settings_getint(PointerByReference settings, String name, IntBuffer val);

    /**
     * Original signature : <code>int fluid_settings_getint(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:148</i>
     */
    int fluid_settings_getint(PointerByReference settings, Pointer name, IntByReference val);

    /**
     * Original signature : <code>int fluid_settings_getint_default(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:151</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_getint_default(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.IntBuffer)} and {@link #fluid_settings_getint_default(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    int fluid_settings_getint_default(Pointer settings, Pointer name, IntByReference val);

    /**
     * Original signature : <code>int fluid_settings_getint_default(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:151</i>
     */
    int fluid_settings_getint_default(PointerByReference settings, String name, IntBuffer val);

    /**
     * Original signature : <code>int fluid_settings_getint_default(fluid_settings_t*, const char*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:151</i>
     */
    int fluid_settings_getint_default(PointerByReference settings, Pointer name, IntByReference val);

    /**
     * Original signature : <code>int fluid_settings_getint_range(fluid_settings_t*, const char*, int*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:154</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_getint_range(com.sun.jna.ptr.PointerByReference, java.lang.String, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #fluid_settings_getint_range(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
     */
    @Deprecated
    int fluid_settings_getint_range(Pointer settings, Pointer name, IntByReference min, IntByReference max);

    /**
     * Original signature : <code>int fluid_settings_getint_range(fluid_settings_t*, const char*, int*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:154</i>
     */
    int fluid_settings_getint_range(PointerByReference settings, String name, IntBuffer min, IntBuffer max);

    /**
     * Original signature : <code>int fluid_settings_getint_range(fluid_settings_t*, const char*, int*, int*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:154</i>
     */
    int fluid_settings_getint_range(PointerByReference settings, Pointer name, IntByReference min, IntByReference max);

    /**
     * Original signature : <code>void fluid_settings_foreach_option(fluid_settings_t*, const char*, void*, fluid_settings_foreach_option_t)</code><br>
     * <i>native declaration : fluidsynth/settings.h:167</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_foreach_option(com.sun.jna.ptr.PointerByReference, java.lang.String, com.sun.jna.Pointer, vavi.sound.midi.fluidsynth.jna.settings.SettingsLibrary.fluid_settings_foreach_option_t)} and {@link #fluid_settings_foreach_option(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer, vavi.sound.midi.fluidsynth.jna.settings.SettingsLibrary.fluid_settings_foreach_option_t)} instead
     */
    @Deprecated
    void fluid_settings_foreach_option(Pointer settings, Pointer name, Pointer data, SettingsLibrary.fluid_settings_foreach_option_t func);

    /**
     * Original signature : <code>void fluid_settings_foreach_option(fluid_settings_t*, const char*, void*, fluid_settings_foreach_option_t)</code><br>
     * <i>native declaration : fluidsynth/settings.h:167</i>
     */
    void fluid_settings_foreach_option(PointerByReference settings, String name, Pointer data, SettingsLibrary.fluid_settings_foreach_option_t func);

    /**
     * Original signature : <code>void fluid_settings_foreach_option(fluid_settings_t*, const char*, void*, fluid_settings_foreach_option_t)</code><br>
     * <i>native declaration : fluidsynth/settings.h:167</i>
     */
    void fluid_settings_foreach_option(PointerByReference settings, Pointer name, Pointer data, SettingsLibrary.fluid_settings_foreach_option_t func);

    /**
     * Original signature : <code>int fluid_settings_option_count(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:171</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_option_count(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_settings_option_count(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_settings_option_count(Pointer settings, Pointer name);

    /**
     * Original signature : <code>int fluid_settings_option_count(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:171</i>
     */
    int fluid_settings_option_count(PointerByReference settings, String name);

    /**
     * Original signature : <code>int fluid_settings_option_count(fluid_settings_t*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:171</i>
     */
    int fluid_settings_option_count(PointerByReference settings, Pointer name);

    /**
     * Original signature : <code>char* fluid_settings_option_concat(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:172</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_settings_option_concat(com.sun.jna.ptr.PointerByReference, java.lang.String, java.lang.String)} and {@link #fluid_settings_option_concat(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    Pointer fluid_settings_option_concat(Pointer settings, Pointer name, Pointer separator);

    /**
     * Original signature : <code>char* fluid_settings_option_concat(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:172</i>
     */
    Pointer fluid_settings_option_concat(PointerByReference settings, String name, String separator);

    /**
     * Original signature : <code>char* fluid_settings_option_concat(fluid_settings_t*, const char*, const char*)</code><br>
     * <i>native declaration : fluidsynth/settings.h:172</i>
     */
    Pointer fluid_settings_option_concat(PointerByReference settings, Pointer name, Pointer separator);

    /**
     * Original signature : <code>void fluid_settings_foreach(fluid_settings_t*, void*, fluid_settings_foreach_t)</code><br>
     * <i>native declaration : fluidsynth/settings.h:186</i><br>
     *
     * @deprecated use the safer method {@link #fluid_settings_foreach(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, vavi.sound.midi.fluidsynth.jna.settings.SettingsLibrary.fluid_settings_foreach_t)} instead
     */
    @Deprecated
    void fluid_settings_foreach(Pointer settings, Pointer data, SettingsLibrary.fluid_settings_foreach_t func);

    /**
     * Original signature : <code>void fluid_settings_foreach(fluid_settings_t*, void*, fluid_settings_foreach_t)</code><br>
     * <i>native declaration : fluidsynth/settings.h:186</i>
     */
    void fluid_settings_foreach(PointerByReference settings, Pointer data, SettingsLibrary.fluid_settings_foreach_t func);

    class fluid_settings_t extends PointerType {

        public fluid_settings_t(Pointer address) {
            super(address);
        }

        public fluid_settings_t() {
            super();
        }
    }

    ;
}
