package vavi.sound.midi.fluidsynth.jna.seqbind;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;


/**
 * JNA Wrapper for library <b>seqbind</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SeqbindLibrary extends Library {

    public static final String JNA_LIBRARY_NAME = "fluidsynth";
    public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SeqbindLibrary.JNA_LIBRARY_NAME);
    public static final SeqbindLibrary INSTANCE = (SeqbindLibrary) Native.load(SeqbindLibrary.JNA_LIBRARY_NAME, SeqbindLibrary.class);

    /**
     * @addtogroup sequencer<br>
     * @{<br> Original signature : <code>fluid_seq_id_t fluid_sequencer_register_fluidsynth(fluid_sequencer_t*, fluid_synth_t*)</code><br>
     * <i>native declaration : fluidsynth/seqbind.h:35</i><br>
     * @deprecated use the safer method {@link #fluid_sequencer_register_fluidsynth(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    short fluid_sequencer_register_fluidsynth(Pointer seq, Pointer synth);

    /**
     * @addtogroup sequencer<br>
     * @{<br> Original signature : <code>fluid_seq_id_t fluid_sequencer_register_fluidsynth(fluid_sequencer_t*, fluid_synth_t*)</code><br>
     * <i>native declaration : fluidsynth/seqbind.h:35</i>
     */
    short fluid_sequencer_register_fluidsynth(PointerByReference seq, PointerByReference synth);

    /**
     * Original signature : <code>int fluid_sequencer_add_midi_event_to_buffer(void*, fluid_midi_event_t*)</code><br>
     * <i>native declaration : fluidsynth/seqbind.h:37</i><br>
     *
     * @deprecated use the safer method {@link #fluid_sequencer_add_midi_event_to_buffer(com.sun.jna.Pointer, com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_sequencer_add_midi_event_to_buffer(Pointer data, Pointer event);

    /**
     * Original signature : <code>int fluid_sequencer_add_midi_event_to_buffer(void*, fluid_midi_event_t*)</code><br>
     * <i>native declaration : fluidsynth/seqbind.h:37</i>
     */
    int fluid_sequencer_add_midi_event_to_buffer(Pointer data, PointerByReference event);

    public static class fluid_midi_event_t extends PointerType {

        public fluid_midi_event_t(Pointer address) {
            super(address);
        }

        public fluid_midi_event_t() {
            super();
        }
    }

    ;
}
