package vavi.sound.midi.fluidsynth.jna.ladspa;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;
import java.nio.ByteBuffer;
/**
 * JNA Wrapper for library <b>ladspa</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface LadspaLibrary extends Library {
	String JNA_LIBRARY_NAME = "fluidsynth";
	NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(LadspaLibrary.JNA_LIBRARY_NAME);
	LadspaLibrary INSTANCE = Native.load(LadspaLibrary.JNA_LIBRARY_NAME, LadspaLibrary.class);
	/**
	 * @defgroup ladspa Effect - LADSPA<br>
	 * @ingroup synth<br>
	 * Functions for configuring the LADSPA effects unit<br>
	 * This header defines useful functions for programmatically manipulating the ladspa<br>
	 * effects unit of the synth that can be retrieved via fluid_synth_get_ladspa_fx().<br>
	 * Using any of those functions requires fluidsynth to be compiled with LADSPA support.<br>
	 * Else all of those functions are useless dummies.<br>
	 * @{<br>
	 * Original signature : <code>int fluid_ladspa_is_active(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:42</i><br>
	 * @deprecated use the safer method {@link #fluid_ladspa_is_active(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_ladspa_is_active(Pointer fx);
	/**
	 * @defgroup ladspa Effect - LADSPA<br>
	 * @ingroup synth<br>
	 * Functions for configuring the LADSPA effects unit<br>
	 * This header defines useful functions for programmatically manipulating the ladspa<br>
	 * effects unit of the synth that can be retrieved via fluid_synth_get_ladspa_fx().<br>
	 * Using any of those functions requires fluidsynth to be compiled with LADSPA support.<br>
	 * Else all of those functions are useless dummies.<br>
	 * @{<br>
	 * Original signature : <code>int fluid_ladspa_is_active(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:42</i>
	 */
	int fluid_ladspa_is_active(PointerByReference fx);
	/**
	 * Original signature : <code>int fluid_ladspa_activate(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:43</i><br>
	 * @deprecated use the safer method {@link #fluid_ladspa_activate(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_ladspa_activate(Pointer fx);
	/**
	 * Original signature : <code>int fluid_ladspa_activate(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:43</i>
	 */
	int fluid_ladspa_activate(PointerByReference fx);
	/**
	 * Original signature : <code>int fluid_ladspa_deactivate(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:44</i><br>
	 * @deprecated use the safer method {@link #fluid_ladspa_deactivate(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_ladspa_deactivate(Pointer fx);
	/**
	 * Original signature : <code>int fluid_ladspa_deactivate(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:44</i>
	 */
	int fluid_ladspa_deactivate(PointerByReference fx);
	/**
	 * Original signature : <code>int fluid_ladspa_reset(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:45</i><br>
	 * @deprecated use the safer method {@link #fluid_ladspa_reset(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_ladspa_reset(Pointer fx);
	/**
	 * Original signature : <code>int fluid_ladspa_reset(fluid_ladspa_fx_t*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:45</i>
	 */
	int fluid_ladspa_reset(PointerByReference fx);
	/**
	 * Original signature : <code>int fluid_ladspa_check(fluid_ladspa_fx_t*, char*, int)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:46</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_check(com.sun.jna.ptr.PointerByReference, java.nio.ByteBuffer, int)} and {@link #fluid_ladspa_check(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int fluid_ladspa_check(Pointer fx, Pointer err, int err_size);
	/**
	 * Original signature : <code>int fluid_ladspa_check(fluid_ladspa_fx_t*, char*, int)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:46</i>
	 */
	int fluid_ladspa_check(PointerByReference fx, ByteBuffer err, int err_size);
	/**
	 * Original signature : <code>int fluid_ladspa_check(fluid_ladspa_fx_t*, char*, int)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:46</i>
	 */
	int fluid_ladspa_check(PointerByReference fx, Pointer err, int err_size);
	/**
	 * Original signature : <code>int fluid_ladspa_host_port_exists(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:48</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_host_port_exists(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_ladspa_host_port_exists(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_ladspa_host_port_exists(Pointer fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_host_port_exists(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:48</i>
	 */
	int fluid_ladspa_host_port_exists(PointerByReference fx, String name);
	/**
	 * Original signature : <code>int fluid_ladspa_host_port_exists(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:48</i>
	 */
	int fluid_ladspa_host_port_exists(PointerByReference fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_add_buffer(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:50</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_add_buffer(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_ladspa_add_buffer(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_ladspa_add_buffer(Pointer fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_add_buffer(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:50</i>
	 */
	int fluid_ladspa_add_buffer(PointerByReference fx, String name);
	/**
	 * Original signature : <code>int fluid_ladspa_add_buffer(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:50</i>
	 */
	int fluid_ladspa_add_buffer(PointerByReference fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_buffer_exists(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:51</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_buffer_exists(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_ladspa_buffer_exists(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_ladspa_buffer_exists(Pointer fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_buffer_exists(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:51</i>
	 */
	int fluid_ladspa_buffer_exists(PointerByReference fx, String name);
	/**
	 * Original signature : <code>int fluid_ladspa_buffer_exists(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:51</i>
	 */
	int fluid_ladspa_buffer_exists(PointerByReference fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_add_effect(fluid_ladspa_fx_t*, const char*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:53</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_add_effect(com.sun.jna.ptr.PointerByReference, java.lang.String, java.lang.String, java.lang.String)} and {@link #fluid_ladspa_add_effect(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_ladspa_add_effect(Pointer fx, Pointer effect_name, Pointer lib_name, Pointer plugin_name);
	/**
	 * Original signature : <code>int fluid_ladspa_add_effect(fluid_ladspa_fx_t*, const char*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:53</i>
	 */
	int fluid_ladspa_add_effect(PointerByReference fx, String effect_name, String lib_name, String plugin_name);
	/**
	 * Original signature : <code>int fluid_ladspa_add_effect(fluid_ladspa_fx_t*, const char*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:53</i>
	 */
	int fluid_ladspa_add_effect(PointerByReference fx, Pointer effect_name, Pointer lib_name, Pointer plugin_name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_can_mix(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:55</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_effect_can_mix(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_ladspa_effect_can_mix(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_ladspa_effect_can_mix(Pointer fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_can_mix(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:55</i>
	 */
	int fluid_ladspa_effect_can_mix(PointerByReference fx, String name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_can_mix(fluid_ladspa_fx_t*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:55</i>
	 */
	int fluid_ladspa_effect_can_mix(PointerByReference fx, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_set_mix(fluid_ladspa_fx_t*, const char*, int, float)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:56</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_effect_set_mix(com.sun.jna.ptr.PointerByReference, java.lang.String, int, float)} and {@link #fluid_ladspa_effect_set_mix(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, int, float)} instead
	 */
	@Deprecated 
	int fluid_ladspa_effect_set_mix(Pointer fx, Pointer name, int mix, float gain);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_set_mix(fluid_ladspa_fx_t*, const char*, int, float)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:56</i>
	 */
	int fluid_ladspa_effect_set_mix(PointerByReference fx, String name, int mix, float gain);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_set_mix(fluid_ladspa_fx_t*, const char*, int, float)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:56</i>
	 */
	int fluid_ladspa_effect_set_mix(PointerByReference fx, Pointer name, int mix, float gain);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_port_exists(fluid_ladspa_fx_t*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:57</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_effect_port_exists(com.sun.jna.ptr.PointerByReference, java.lang.String, java.lang.String)} and {@link #fluid_ladspa_effect_port_exists(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_ladspa_effect_port_exists(Pointer fx, Pointer effect_name, Pointer port_name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_port_exists(fluid_ladspa_fx_t*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:57</i>
	 */
	int fluid_ladspa_effect_port_exists(PointerByReference fx, String effect_name, String port_name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_port_exists(fluid_ladspa_fx_t*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:57</i>
	 */
	int fluid_ladspa_effect_port_exists(PointerByReference fx, Pointer effect_name, Pointer port_name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_set_control(fluid_ladspa_fx_t*, const char*, const char*, float)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:58</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_effect_set_control(com.sun.jna.ptr.PointerByReference, java.lang.String, java.lang.String, float)} and {@link #fluid_ladspa_effect_set_control(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer, float)} instead
	 */
	@Deprecated 
	int fluid_ladspa_effect_set_control(Pointer fx, Pointer effect_name, Pointer port_name, float val);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_set_control(fluid_ladspa_fx_t*, const char*, const char*, float)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:58</i>
	 */
	int fluid_ladspa_effect_set_control(PointerByReference fx, String effect_name, String port_name, float val);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_set_control(fluid_ladspa_fx_t*, const char*, const char*, float)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:58</i>
	 */
	int fluid_ladspa_effect_set_control(PointerByReference fx, Pointer effect_name, Pointer port_name, float val);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_link(fluid_ladspa_fx_t*, const char*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:60</i><br>
	 * @deprecated use the safer methods {@link #fluid_ladspa_effect_link(com.sun.jna.ptr.PointerByReference, java.lang.String, java.lang.String, java.lang.String)} and {@link #fluid_ladspa_effect_link(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_ladspa_effect_link(Pointer fx, Pointer effect_name, Pointer port_name, Pointer name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_link(fluid_ladspa_fx_t*, const char*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:60</i>
	 */
	int fluid_ladspa_effect_link(PointerByReference fx, String effect_name, String port_name, String name);
	/**
	 * Original signature : <code>int fluid_ladspa_effect_link(fluid_ladspa_fx_t*, const char*, const char*, const char*)</code><br>
	 * <i>native declaration : fluidsynth/ladspa.h:60</i>
	 */
	int fluid_ladspa_effect_link(PointerByReference fx, Pointer effect_name, Pointer port_name, Pointer name);
	public static class fluid_ladspa_fx_t extends PointerType {
		public fluid_ladspa_fx_t(Pointer address) {
			super(address);
		}
		public fluid_ladspa_fx_t() {
			super();
		}
	};
}
