package vavi.sound.sampled.jna.codec;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;


/**
 * vorbis_block is a single block of data to be processed as part of<br>
 * the analysis/synthesis stream; it belongs to a specific logical<br>
 * bitstream, but is independent of other vorbis_blocks belonging to<br>
 * that logical bitstream. ************************************************<br>
 * <i>native declaration : List<String>vorbis/codec.h:124</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class alloc_chain extends Structure {

    /** C type : void* */
    public Pointer ptr;
    /** C type : alloc_chain* */
    public Pointer next;

    public alloc_chain() {
        super();
    }

    @Override
    protected List<String> getFieldOrder() {
        return Arrays.asList("ptr", "next");
    }

    /**
     * @param ptr  C type : void*<br>
     * @param next C type : alloc_chain*
     */
    public alloc_chain(Pointer ptr, Pointer next) {
        super();
        this.ptr = ptr;
        this.next = next;
    }

    public alloc_chain(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends alloc_chain implements Structure.ByReference {

    }

    public static class ByValue extends alloc_chain implements Structure.ByValue {

    }

}
