package vavi.sound.sampled.jna.codec;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;
import vavi.sound.sampled.jna.ogg.ogg_packet;


/**
 * JNA Wrapper for library <b>codec</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CodecLibrary extends Library {

    String JNA_LIBRARY_NAME = "vorbis";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(CodecLibrary.JNA_LIBRARY_NAME);
    CodecLibrary INSTANCE = Native.load(CodecLibrary.JNA_LIBRARY_NAME, CodecLibrary.class);
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_FALSE = -1;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EOF = -2;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_HOLE = -3;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EREAD = -128;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EFAULT = -129;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EIMPL = -130;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EINVAL = -131;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_ENOTVORBIS = -132;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EBADHEADER = -133;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EVERSION = -134;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_ENOTAUDIO = -135;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EBADPACKET = -136;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_EBADLINK = -137;
    /** <i>native declaration : List<String>vorbis/codec.h</i> */
    int OV_ENOSEEK = -138;

    /**
     * Vorbis PRIMITIVES: general<br>
     * Original signature : <code>void vorbis_info_init(vorbis_info*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:162</i>
     */
    void vorbis_info_init(vorbis_info vi);

    /**
     * Original signature : <code>void vorbis_info_clear(vorbis_info*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:163</i>
     */
    void vorbis_info_clear(vorbis_info vi);

    /**
     * Original signature : <code>int vorbis_info_blocksize(vorbis_info*, int)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:164</i>
     */
    int vorbis_info_blocksize(vorbis_info vi, int zo);

    /**
     * Original signature : <code>void vorbis_comment_init(vorbis_comment*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:165</i>
     */
    void vorbis_comment_init(vorbis_comment vc);

    /**
     * Original signature : <code>void vorbis_comment_add(vorbis_comment*, const char*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:166</i><br>
     *
     * @deprecated use the safer methods {@link #vorbis_comment_add(vavi.sound.sampled.jna.codec.vorbis_comment, java.lang.String)} and {@link #vorbis_comment_add(vavi.sound.sampled.jna.codec.vorbis_comment, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    void vorbis_comment_add(vorbis_comment vc, Pointer comment);

    /**
     * Original signature : <code>void vorbis_comment_add(vorbis_comment*, const char*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:166</i>
     */
    void vorbis_comment_add(vorbis_comment vc, String comment);

    /**
     * Original signature : <code>void vorbis_comment_add_tag(vorbis_comment*, const char*, const char*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:167</i><br>
     *
     * @deprecated use the safer methods {@link #vorbis_comment_add_tag(vavi.sound.sampled.jna.codec.vorbis_comment, java.lang.String, java.lang.String)} and {@link #vorbis_comment_add_tag(vavi.sound.sampled.jna.codec.vorbis_comment, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    void vorbis_comment_add_tag(vorbis_comment vc, Pointer tag, Pointer contents);

    /**
     * Original signature : <code>void vorbis_comment_add_tag(vorbis_comment*, const char*, const char*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:167</i>
     */
    void vorbis_comment_add_tag(vorbis_comment vc, String tag, String contents);

    /**
     * Original signature : <code>char* vorbis_comment_query(vorbis_comment*, const char*, int)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:169</i><br>
     *
     * @deprecated use the safer methods {@link #vorbis_comment_query(vavi.sound.sampled.jna.codec.vorbis_comment, java.lang.String, int)} and {@link #vorbis_comment_query(vavi.sound.sampled.jna.codec.vorbis_comment, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    Pointer vorbis_comment_query(vorbis_comment vc, Pointer tag, int count);

    /**
     * Original signature : <code>char* vorbis_comment_query(vorbis_comment*, const char*, int)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:169</i>
     */
    Pointer vorbis_comment_query(vorbis_comment vc, String tag, int count);

    /**
     * Original signature : <code>int vorbis_comment_query_count(vorbis_comment*, const char*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:170</i><br>
     *
     * @deprecated use the safer methods {@link #vorbis_comment_query_count(vavi.sound.sampled.jna.codec.vorbis_comment, java.lang.String)} and {@link #vorbis_comment_query_count(vavi.sound.sampled.jna.codec.vorbis_comment, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int vorbis_comment_query_count(vorbis_comment vc, Pointer tag);

    /**
     * Original signature : <code>int vorbis_comment_query_count(vorbis_comment*, const char*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:170</i>
     */
    int vorbis_comment_query_count(vorbis_comment vc, String tag);

    /**
     * Original signature : <code>void vorbis_comment_clear(vorbis_comment*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:171</i>
     */
    void vorbis_comment_clear(vorbis_comment vc);

    /**
     * Original signature : <code>int vorbis_block_init(vorbis_dsp_state*, vorbis_block*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:173</i>
     */
    int vorbis_block_init(vorbis_dsp_state v, vorbis_block vb);

    /**
     * Original signature : <code>int vorbis_block_clear(vorbis_block*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:174</i>
     */
    int vorbis_block_clear(vorbis_block vb);

    /**
     * Original signature : <code>void vorbis_dsp_clear(vorbis_dsp_state*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:175</i>
     */
    void vorbis_dsp_clear(vorbis_dsp_state v);

    /**
     * Original signature : <code>double vorbis_granule_time(vorbis_dsp_state*, ogg_int64_t)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:176</i>
     */
    double vorbis_granule_time(vorbis_dsp_state v, long granulepos);

    /**
     * Original signature : <code>char* vorbis_version_string()</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:179</i>
     */
    Pointer vorbis_version_string();

    /**
     * Vorbis PRIMITIVES: analysis/DSP layer ***************************<br>
     * Original signature : <code>int vorbis_analysis_init(vorbis_dsp_state*, vorbis_info*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:183</i>
     */
    int vorbis_analysis_init(vorbis_dsp_state v, vorbis_info vi);

    /**
     * Original signature : <code>int vorbis_commentheader_out(vorbis_comment*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:184</i>
     */
    int vorbis_commentheader_out(vorbis_comment vc, ogg_packet op);

    /**
     * Original signature : <code>int vorbis_analysis_headerout(vorbis_dsp_state*, vorbis_comment*, ogg_packet*, ogg_packet*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:185</i>
     */
    int vorbis_analysis_headerout(vorbis_dsp_state v, vorbis_comment vc, ogg_packet op, ogg_packet op_comm, ogg_packet op_code);

    /**
     * Original signature : <code>float** vorbis_analysis_buffer(vorbis_dsp_state*, int)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:190</i>
     */
    PointerByReference vorbis_analysis_buffer(vorbis_dsp_state v, int vals);

    /**
     * Original signature : <code>int vorbis_analysis_wrote(vorbis_dsp_state*, int)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:191</i>
     */
    int vorbis_analysis_wrote(vorbis_dsp_state v, int vals);

    /**
     * Original signature : <code>int vorbis_analysis_blockout(vorbis_dsp_state*, vorbis_block*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:192</i>
     */
    int vorbis_analysis_blockout(vorbis_dsp_state v, vorbis_block vb);

    /**
     * Original signature : <code>int vorbis_analysis(vorbis_block*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:193</i>
     */
    int vorbis_analysis(vorbis_block vb, ogg_packet op);

    /**
     * Original signature : <code>int vorbis_bitrate_addblock(vorbis_block*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:195</i>
     */
    int vorbis_bitrate_addblock(vorbis_block vb);

    /**
     * Original signature : <code>int vorbis_bitrate_flushpacket(vorbis_dsp_state*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:196</i>
     */
    int vorbis_bitrate_flushpacket(vorbis_dsp_state vd, ogg_packet op);

    /**
     * Vorbis PRIMITIVES: synthesis layer ******************************<br>
     * Original signature : <code>int vorbis_synthesis_idheader(ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:200</i>
     */
    int vorbis_synthesis_idheader(ogg_packet op);

    /**
     * Original signature : <code>int vorbis_synthesis_headerin(vorbis_info*, vorbis_comment*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:201</i>
     */
    int vorbis_synthesis_headerin(vorbis_info vi, vorbis_comment vc, ogg_packet op);

    /**
     * Original signature : <code>int vorbis_synthesis_init(vorbis_dsp_state*, vorbis_info*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:204</i>
     */
    int vorbis_synthesis_init(vorbis_dsp_state v, vorbis_info vi);

    /**
     * Original signature : <code>int vorbis_synthesis_restart(vorbis_dsp_state*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:205</i>
     */
    int vorbis_synthesis_restart(vorbis_dsp_state v);

    /**
     * Original signature : <code>int vorbis_synthesis(vorbis_block*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:206</i>
     */
    int vorbis_synthesis(vorbis_block vb, ogg_packet op);

    /**
     * Original signature : <code>int vorbis_synthesis_trackonly(vorbis_block*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:207</i>
     */
    int vorbis_synthesis_trackonly(vorbis_block vb, ogg_packet op);

    /**
     * Original signature : <code>int vorbis_synthesis_blockin(vorbis_dsp_state*, vorbis_block*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:208</i>
     */
    int vorbis_synthesis_blockin(vorbis_dsp_state v, vorbis_block vb);

    /**
     * Original signature : <code>int vorbis_synthesis_pcmout(vorbis_dsp_state*, float***)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:209</i>
     */
    int vorbis_synthesis_pcmout(vorbis_dsp_state v, PointerByReference pcm);

    /**
     * Original signature : <code>int vorbis_synthesis_lapout(vorbis_dsp_state*, float***)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:210</i>
     */
    int vorbis_synthesis_lapout(vorbis_dsp_state v, PointerByReference pcm);

    /**
     * Original signature : <code>int vorbis_synthesis_read(vorbis_dsp_state*, int)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:211</i>
     */
    int vorbis_synthesis_read(vorbis_dsp_state v, int samples);

    /**
     * Original signature : <code>long vorbis_packet_blocksize(vorbis_info*, ogg_packet*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:212</i>
     */
    NativeLong vorbis_packet_blocksize(vorbis_info vi, ogg_packet op);

    /**
     * Original signature : <code>int vorbis_synthesis_halfrate(vorbis_info*, int)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:214</i>
     */
    int vorbis_synthesis_halfrate(vorbis_info v, int flag);

    /**
     * Original signature : <code>int vorbis_synthesis_halfrate_p(vorbis_info*)</code><br>
     * <i>native declaration : List<String>vorbis/codec.h:215</i>
     */
    int vorbis_synthesis_halfrate_p(vorbis_info v);
}
