package vavi.sound.midi.fluidsynth.jna.event;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;
/**
 * JNA Wrapper for library <b>event</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface EventLibrary extends Library {
	String JNA_LIBRARY_NAME = "fluidsynth";
	NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(EventLibrary.JNA_LIBRARY_NAME);
	EventLibrary INSTANCE = Native.load(EventLibrary.JNA_LIBRARY_NAME, EventLibrary.class);
	/**
	 * Sequencer event type enumeration.<br>
	 * <i>native declaration : fluidsynth/event.h:40</i><br>
	 * enum values
	 */
	public static interface fluid_seq_event_type {
		/**
		 * < Note event with duration<br>
		 * <i>native declaration : fluidsynth/event.h:42</i>
		 */
		int FLUID_SEQ_NOTE = 0;
		/**
		 * < Note on event<br>
		 * <i>native declaration : fluidsynth/event.h:43</i>
		 */
		int FLUID_SEQ_NOTEON = 1;
		/**
		 * < Note off event<br>
		 * <i>native declaration : fluidsynth/event.h:44</i>
		 */
		int FLUID_SEQ_NOTEOFF = 2;
		/**
		 * < All sounds off event<br>
		 * <i>native declaration : fluidsynth/event.h:45</i>
		 */
		int FLUID_SEQ_ALLSOUNDSOFF = 3;
		/**
		 * < All notes off event<br>
		 * <i>native declaration : fluidsynth/event.h:46</i>
		 */
		int FLUID_SEQ_ALLNOTESOFF = 4;
		/**
		 * < Bank select message<br>
		 * <i>native declaration : fluidsynth/event.h:47</i>
		 */
		int FLUID_SEQ_BANKSELECT = 5;
		/**
		 * < Program change message<br>
		 * <i>native declaration : fluidsynth/event.h:48</i>
		 */
		int FLUID_SEQ_PROGRAMCHANGE = 6;
		/**
		 * < Program select message<br>
		 * <i>native declaration : fluidsynth/event.h:49</i>
		 */
		int FLUID_SEQ_PROGRAMSELECT = 7;
		/**
		 * < Pitch bend message<br>
		 * <i>native declaration : fluidsynth/event.h:50</i>
		 */
		int FLUID_SEQ_PITCHBEND = 8;
		/**
		 * < Pitch wheel sensitivity set message @since 1.1.0 was misspelled previously<br>
		 * <i>native declaration : fluidsynth/event.h:51</i>
		 */
		int FLUID_SEQ_PITCHWHEELSENS = 9;
		/**
		 * < Modulation controller event<br>
		 * <i>native declaration : fluidsynth/event.h:52</i>
		 */
		int FLUID_SEQ_MODULATION = 10;
		/**
		 * < Sustain controller event<br>
		 * <i>native declaration : fluidsynth/event.h:53</i>
		 */
		int FLUID_SEQ_SUSTAIN = 11;
		/**
		 * < MIDI control change event<br>
		 * <i>native declaration : fluidsynth/event.h:54</i>
		 */
		int FLUID_SEQ_CONTROLCHANGE = 12;
		/**
		 * < Stereo pan set event<br>
		 * <i>native declaration : fluidsynth/event.h:55</i>
		 */
		int FLUID_SEQ_PAN = 13;
		/**
		 * < Volume set event<br>
		 * <i>native declaration : fluidsynth/event.h:56</i>
		 */
		int FLUID_SEQ_VOLUME = 14;
		/**
		 * < Reverb send set event<br>
		 * <i>native declaration : fluidsynth/event.h:57</i>
		 */
		int FLUID_SEQ_REVERBSEND = 15;
		/**
		 * < Chorus send set event<br>
		 * <i>native declaration : fluidsynth/event.h:58</i>
		 */
		int FLUID_SEQ_CHORUSSEND = 16;
		/**
		 * < Timer event (useful for giving a callback at a certain time)<br>
		 * <i>native declaration : fluidsynth/event.h:59</i>
		 */
		int FLUID_SEQ_TIMER = 17;
		/**
		 * < Channel aftertouch event @since 1.1.0<br>
		 * <i>native declaration : fluidsynth/event.h:60</i>
		 */
		int FLUID_SEQ_CHANNELPRESSURE = 18;
		/**
		 * < Polyphonic aftertouch event @since 2.0.0<br>
		 * <i>native declaration : fluidsynth/event.h:61</i>
		 */
		int FLUID_SEQ_KEYPRESSURE = 19;
		/**
		 * < System reset event @since 1.1.0<br>
		 * <i>native declaration : fluidsynth/event.h:62</i>
		 */
		int FLUID_SEQ_SYSTEMRESET = 20;
		/**
		 * < Called when a sequencer client is being unregistered. @since 1.1.0<br>
		 * <i>native declaration : fluidsynth/event.h:63</i>
		 */
		int FLUID_SEQ_UNREGISTERING = 21;
		/**
		 * < Sets a new time scale for the sequencer @since 2.2.0<br>
		 * <i>native declaration : fluidsynth/event.h:64</i>
		 */
		int FLUID_SEQ_SCALE = 22;
		/**
		 * < @internal Defines the count of events enums @warning This symbol <br>
		 * is not part of the public API and ABI stability guarantee and <br>
		 * may change at any time!<br>
		 * <i>native declaration : fluidsynth/event.h:65</i>
		 */
		int FLUID_SEQ_LASTEVENT = 23;
	};
	/**
	 * @startlifecycle{Sequencer Event}<br>
	 * Original signature : <code>fluid_event_t* new_fluid_event()</code><br>
	 * <i>native declaration : fluidsynth/event.h:72</i>
	 */
	PointerByReference new_fluid_event();
	/**
	 * Original signature : <code>void delete_fluid_event(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:73</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_event(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_event(Pointer evt);
	/**
	 * Original signature : <code>void delete_fluid_event(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:73</i>
	 */
	void delete_fluid_event(PointerByReference evt);
	/**
	 * Initializing events<br>
	 * Original signature : <code>void fluid_event_set_source(fluid_event_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/event.h:77</i><br>
	 * @deprecated use the safer method {@link #fluid_event_set_source(com.sun.jna.ptr.PointerByReference, short)} instead
	 */
	@Deprecated 
	void fluid_event_set_source(Pointer evt, short src);
	/**
	 * Initializing events<br>
	 * Original signature : <code>void fluid_event_set_source(fluid_event_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/event.h:77</i>
	 */
	void fluid_event_set_source(PointerByReference evt, short src);
	/**
	 * Original signature : <code>void fluid_event_set_dest(fluid_event_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/event.h:78</i><br>
	 * @deprecated use the safer method {@link #fluid_event_set_dest(com.sun.jna.ptr.PointerByReference, short)} instead
	 */
	@Deprecated 
	void fluid_event_set_dest(Pointer evt, short dest);
	/**
	 * Original signature : <code>void fluid_event_set_dest(fluid_event_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/event.h:78</i>
	 */
	void fluid_event_set_dest(PointerByReference evt, short dest);
	/**
	 * Timer events<br>
	 * Original signature : <code>void fluid_event_timer(fluid_event_t*, void*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:81</i><br>
	 * @deprecated use the safer method {@link #fluid_event_timer(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	void fluid_event_timer(Pointer evt, Pointer data);
	/**
	 * Timer events<br>
	 * Original signature : <code>void fluid_event_timer(fluid_event_t*, void*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:81</i>
	 */
	void fluid_event_timer(PointerByReference evt, Pointer data);
	/**
	 * Note events<br>
	 * Original signature : <code>void fluid_event_note(fluid_event_t*, int, short, short, unsigned int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:84</i><br>
	 * @deprecated use the safer method {@link #fluid_event_note(com.sun.jna.ptr.PointerByReference, int, short, short, int)} instead
	 */
	@Deprecated 
	void fluid_event_note(Pointer evt, int channel, short key, short vel, int duration);
	/**
	 * Note events<br>
	 * Original signature : <code>void fluid_event_note(fluid_event_t*, int, short, short, unsigned int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:84</i>
	 */
	void fluid_event_note(PointerByReference evt, int channel, short key, short vel, int duration);
	/**
	 * Original signature : <code>void fluid_event_noteon(fluid_event_t*, int, short, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:88</i><br>
	 * @deprecated use the safer method {@link #fluid_event_noteon(com.sun.jna.ptr.PointerByReference, int, short, short)} instead
	 */
	@Deprecated 
	void fluid_event_noteon(Pointer evt, int channel, short key, short vel);
	/**
	 * Original signature : <code>void fluid_event_noteon(fluid_event_t*, int, short, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:88</i>
	 */
	void fluid_event_noteon(PointerByReference evt, int channel, short key, short vel);
	/**
	 * Original signature : <code>void fluid_event_noteoff(fluid_event_t*, int, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:89</i><br>
	 * @deprecated use the safer method {@link #fluid_event_noteoff(com.sun.jna.ptr.PointerByReference, int, short)} instead
	 */
	@Deprecated 
	void fluid_event_noteoff(Pointer evt, int channel, short key);
	/**
	 * Original signature : <code>void fluid_event_noteoff(fluid_event_t*, int, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:89</i>
	 */
	void fluid_event_noteoff(PointerByReference evt, int channel, short key);
	/**
	 * Original signature : <code>void fluid_event_all_sounds_off(fluid_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:90</i><br>
	 * @deprecated use the safer method {@link #fluid_event_all_sounds_off(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	void fluid_event_all_sounds_off(Pointer evt, int channel);
	/**
	 * Original signature : <code>void fluid_event_all_sounds_off(fluid_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:90</i>
	 */
	void fluid_event_all_sounds_off(PointerByReference evt, int channel);
	/**
	 * Original signature : <code>void fluid_event_all_notes_off(fluid_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:91</i><br>
	 * @deprecated use the safer method {@link #fluid_event_all_notes_off(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	void fluid_event_all_notes_off(Pointer evt, int channel);
	/**
	 * Original signature : <code>void fluid_event_all_notes_off(fluid_event_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:91</i>
	 */
	void fluid_event_all_notes_off(PointerByReference evt, int channel);
	/**
	 * Instrument selection<br>
	 * Original signature : <code>void fluid_event_bank_select(fluid_event_t*, int, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:94</i><br>
	 * @deprecated use the safer method {@link #fluid_event_bank_select(com.sun.jna.ptr.PointerByReference, int, short)} instead
	 */
	@Deprecated 
	void fluid_event_bank_select(Pointer evt, int channel, short bank_num);
	/**
	 * Instrument selection<br>
	 * Original signature : <code>void fluid_event_bank_select(fluid_event_t*, int, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:94</i>
	 */
	void fluid_event_bank_select(PointerByReference evt, int channel, short bank_num);
	/**
	 * Original signature : <code>void fluid_event_program_change(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:95</i><br>
	 * @deprecated use the safer method {@link #fluid_event_program_change(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_program_change(Pointer evt, int channel, int preset_num);
	/**
	 * Original signature : <code>void fluid_event_program_change(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:95</i>
	 */
	void fluid_event_program_change(PointerByReference evt, int channel, int preset_num);
	/**
	 * Original signature : <code>void fluid_event_program_select(fluid_event_t*, int, unsigned int, short, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:96</i><br>
	 * @deprecated use the safer method {@link #fluid_event_program_select(com.sun.jna.ptr.PointerByReference, int, int, short, short)} instead
	 */
	@Deprecated 
	void fluid_event_program_select(Pointer evt, int channel, int sfont_id, short bank_num, short preset_num);
	/**
	 * Original signature : <code>void fluid_event_program_select(fluid_event_t*, int, unsigned int, short, short)</code><br>
	 * <i>native declaration : fluidsynth/event.h:96</i>
	 */
	void fluid_event_program_select(PointerByReference evt, int channel, int sfont_id, short bank_num, short preset_num);
	/**
	 * Real-time generic instrument controllers<br>
	 * Original signature : <code>void fluid_event_control_change(fluid_event_t*, int, short, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:100</i><br>
	 * @deprecated use the safer method {@link #fluid_event_control_change(com.sun.jna.ptr.PointerByReference, int, short, int)} instead
	 */
	@Deprecated 
	void fluid_event_control_change(Pointer evt, int channel, short control, int val);
	/**
	 * Real-time generic instrument controllers<br>
	 * Original signature : <code>void fluid_event_control_change(fluid_event_t*, int, short, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:100</i>
	 */
	void fluid_event_control_change(PointerByReference evt, int channel, short control, int val);
	/**
	 * Real-time instrument controllers shortcuts<br>
	 * Original signature : <code>void fluid_event_pitch_bend(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:103</i><br>
	 * @deprecated use the safer method {@link #fluid_event_pitch_bend(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_pitch_bend(Pointer evt, int channel, int val);
	/**
	 * Real-time instrument controllers shortcuts<br>
	 * Original signature : <code>void fluid_event_pitch_bend(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:103</i>
	 */
	void fluid_event_pitch_bend(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_pitch_wheelsens(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:104</i><br>
	 * @deprecated use the safer method {@link #fluid_event_pitch_wheelsens(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_pitch_wheelsens(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_pitch_wheelsens(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:104</i>
	 */
	void fluid_event_pitch_wheelsens(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_modulation(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:105</i><br>
	 * @deprecated use the safer method {@link #fluid_event_modulation(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_modulation(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_modulation(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:105</i>
	 */
	void fluid_event_modulation(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_sustain(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:106</i><br>
	 * @deprecated use the safer method {@link #fluid_event_sustain(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_sustain(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_sustain(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:106</i>
	 */
	void fluid_event_sustain(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_pan(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:107</i><br>
	 * @deprecated use the safer method {@link #fluid_event_pan(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_pan(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_pan(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:107</i>
	 */
	void fluid_event_pan(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_volume(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:108</i><br>
	 * @deprecated use the safer method {@link #fluid_event_volume(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_volume(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_volume(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:108</i>
	 */
	void fluid_event_volume(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_reverb_send(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:109</i><br>
	 * @deprecated use the safer method {@link #fluid_event_reverb_send(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_reverb_send(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_reverb_send(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:109</i>
	 */
	void fluid_event_reverb_send(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_chorus_send(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:110</i><br>
	 * @deprecated use the safer method {@link #fluid_event_chorus_send(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_chorus_send(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_chorus_send(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:110</i>
	 */
	void fluid_event_chorus_send(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_key_pressure(fluid_event_t*, int, short, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:112</i><br>
	 * @deprecated use the safer method {@link #fluid_event_key_pressure(com.sun.jna.ptr.PointerByReference, int, short, int)} instead
	 */
	@Deprecated 
	void fluid_event_key_pressure(Pointer evt, int channel, short key, int val);
	/**
	 * Original signature : <code>void fluid_event_key_pressure(fluid_event_t*, int, short, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:112</i>
	 */
	void fluid_event_key_pressure(PointerByReference evt, int channel, short key, int val);
	/**
	 * Original signature : <code>void fluid_event_channel_pressure(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:113</i><br>
	 * @deprecated use the safer method {@link #fluid_event_channel_pressure(com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	void fluid_event_channel_pressure(Pointer evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_channel_pressure(fluid_event_t*, int, int)</code><br>
	 * <i>native declaration : fluidsynth/event.h:113</i>
	 */
	void fluid_event_channel_pressure(PointerByReference evt, int channel, int val);
	/**
	 * Original signature : <code>void fluid_event_system_reset(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:114</i><br>
	 * @deprecated use the safer method {@link #fluid_event_system_reset(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void fluid_event_system_reset(Pointer evt);
	/**
	 * Original signature : <code>void fluid_event_system_reset(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:114</i>
	 */
	void fluid_event_system_reset(PointerByReference evt);
	/**
	 * Only when unregistering clients<br>
	 * Original signature : <code>void fluid_event_unregistering(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:117</i><br>
	 * @deprecated use the safer method {@link #fluid_event_unregistering(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void fluid_event_unregistering(Pointer evt);
	/**
	 * Only when unregistering clients<br>
	 * Original signature : <code>void fluid_event_unregistering(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:117</i>
	 */
	void fluid_event_unregistering(PointerByReference evt);
	/**
	 * Original signature : <code>void fluid_event_scale(fluid_event_t*, double)</code><br>
	 * <i>native declaration : fluidsynth/event.h:119</i><br>
	 * @deprecated use the safer method {@link #fluid_event_scale(com.sun.jna.ptr.PointerByReference, double)} instead
	 */
	@Deprecated 
	void fluid_event_scale(Pointer evt, double new_scale);
	/**
	 * Original signature : <code>void fluid_event_scale(fluid_event_t*, double)</code><br>
	 * <i>native declaration : fluidsynth/event.h:119</i>
	 */
	void fluid_event_scale(PointerByReference evt, double new_scale);
	/**
	 * Original signature : <code>int fluid_event_from_midi_event(fluid_event_t*, const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:120</i><br>
	 * @deprecated use the safer method {@link #fluid_event_from_midi_event(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_from_midi_event(Pointer fluid_event_tPtr1, Pointer fluid_midi_event_tPtr1);
	/**
	 * Original signature : <code>int fluid_event_from_midi_event(fluid_event_t*, const fluid_midi_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:120</i>
	 */
	int fluid_event_from_midi_event(PointerByReference fluid_event_tPtr1, PointerByReference fluid_midi_event_tPtr1);
	/**
	 * Accessing event data<br>
	 * Original signature : <code>int fluid_event_get_type(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:123</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_type(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_get_type(Pointer evt);
	/**
	 * Accessing event data<br>
	 * Original signature : <code>int fluid_event_get_type(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:123</i>
	 */
	int fluid_event_get_type(PointerByReference evt);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_event_get_source(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:124</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_source(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	short fluid_event_get_source(Pointer evt);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_event_get_source(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:124</i>
	 */
	short fluid_event_get_source(PointerByReference evt);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_event_get_dest(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:125</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_dest(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	short fluid_event_get_dest(Pointer evt);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_event_get_dest(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:125</i>
	 */
	short fluid_event_get_dest(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_event_get_channel(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:126</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_channel(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_get_channel(Pointer evt);
	/**
	 * Original signature : <code>int fluid_event_get_channel(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:126</i>
	 */
	int fluid_event_get_channel(PointerByReference evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_key(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:127</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_key(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	EventLibrary.FLUIDSYNTH_API fluid_event_get_key(Pointer evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_key(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:127</i>
	 */
	EventLibrary.FLUIDSYNTH_API fluid_event_get_key(PointerByReference evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_velocity(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:128</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_velocity(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	EventLibrary.FLUIDSYNTH_API fluid_event_get_velocity(Pointer evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_velocity(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:128</i>
	 */
	EventLibrary.FLUIDSYNTH_API fluid_event_get_velocity(PointerByReference evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_control(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:129</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_control(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	EventLibrary.FLUIDSYNTH_API fluid_event_get_control(Pointer evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_control(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:129</i>
	 */
	EventLibrary.FLUIDSYNTH_API fluid_event_get_control(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_event_get_value(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:130</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_value(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_get_value(Pointer evt);
	/**
	 * Original signature : <code>int fluid_event_get_value(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:130</i>
	 */
	int fluid_event_get_value(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_event_get_program(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:131</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_program(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_get_program(Pointer evt);
	/**
	 * Original signature : <code>int fluid_event_get_program(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:131</i>
	 */
	int fluid_event_get_program(PointerByReference evt);
	/**
	 * Original signature : <code>void* fluid_event_get_data(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:132</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_data(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	Pointer fluid_event_get_data(Pointer evt);
	/**
	 * Original signature : <code>void* fluid_event_get_data(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:132</i>
	 */
	Pointer fluid_event_get_data(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_event_get_duration(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:133</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_duration(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_get_duration(Pointer evt);
	/**
	 * Original signature : <code>int fluid_event_get_duration(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:133</i>
	 */
	int fluid_event_get_duration(PointerByReference evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_bank(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:134</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_bank(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	EventLibrary.FLUIDSYNTH_API fluid_event_get_bank(Pointer evt);
	/**
	 * Original signature : <code>short FLUIDSYNTH_API fluid_event_get_bank(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:134</i>
	 */
	EventLibrary.FLUIDSYNTH_API fluid_event_get_bank(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_event_get_pitch(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:135</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_pitch(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_get_pitch(Pointer evt);
	/**
	 * Original signature : <code>int fluid_event_get_pitch(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:135</i>
	 */
	int fluid_event_get_pitch(PointerByReference evt);
	/**
	 * Original signature : <code>double fluid_event_get_scale(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:136</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_scale(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	double fluid_event_get_scale(Pointer evt);
	/**
	 * Original signature : <code>double fluid_event_get_scale(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:136</i>
	 */
	double fluid_event_get_scale(PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_event_get_sfont_id(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:137</i><br>
	 * @deprecated use the safer method {@link #fluid_event_get_sfont_id(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_event_get_sfont_id(Pointer evt);
	/**
	 * Original signature : <code>int fluid_event_get_sfont_id(fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/event.h:137</i>
	 */
	int fluid_event_get_sfont_id(PointerByReference evt);
	public static class FLUIDSYNTH_API extends PointerType {
		public FLUIDSYNTH_API(Pointer address) {
			super(address);
		}
		public FLUIDSYNTH_API() {
			super();
		}
	};
}
