package vavi.sound.sampled.jna.lame;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /opt/homebrew/Cellar/lame/3.100/include/lame/lame.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class lame_version_t extends Structure {
	public int major;
	public int minor;
	/** 0 if not an alpha version */
	public int alpha;
	/** 0 if not a beta version */
	public int beta;
	public int psy_major;
	public int psy_minor;
	/** 0 if not an alpha version */
	public int psy_alpha;
	/** 0 if not a beta version */
	public int psy_beta;
	/**
	 * Don't make assumptions about the contents!<br>
	 * C type : const char*
	 */
	public Pointer features;
	public lame_version_t() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("major", "minor", "alpha", "beta", "psy_major", "psy_minor", "psy_alpha", "psy_beta", "features");
	}
	/**
	 * @param alpha 0 if not an alpha version<br>
	 * @param beta 0 if not a beta version<br>
	 * @param psy_alpha 0 if not an alpha version<br>
	 * @param psy_beta 0 if not a beta version<br>
	 * @param features Don't make assumptions about the contents!<br>
	 * C type : const char*
	 */
	public lame_version_t(int major, int minor, int alpha, int beta, int psy_major, int psy_minor, int psy_alpha, int psy_beta, Pointer features) {
		super();
		this.major = major;
		this.minor = minor;
		this.alpha = alpha;
		this.beta = beta;
		this.psy_major = psy_major;
		this.psy_minor = psy_minor;
		this.psy_alpha = psy_alpha;
		this.psy_beta = psy_beta;
		this.features = features;
	}
	public lame_version_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends lame_version_t implements Structure.ByReference {
		
	};
	public static class ByValue extends lame_version_t implements Structure.ByValue {
		
	};
}
