package vavi.sound.sampled.jna.lame;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /opt/homebrew/Cellar/lame/3.100/include/lame/lame.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class mp3data_struct extends Structure {
	/**
	 * 1 if header was parsed and following data was<br>
	 * computed
	 */
	public int header_parsed;
	/** number of channels */
	public int stereo;
	/** sample rate */
	public int samplerate;
	/** bitrate */
	public int bitrate;
	/** mp3 frame type */
	public int mode;
	/** mp3 frame type */
	public int mode_ext;
	/** number of samples per mp3 frame */
	public int framesize;
	/** number of samples in mp3 file. */
	public NativeLong nsamp;
	/** total number of frames in mp3 file */
	public int totalframes;
	/** frames decoded counter */
	public int framenum;
	public mp3data_struct() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("header_parsed", "stereo", "samplerate", "bitrate", "mode", "mode_ext", "framesize", "nsamp", "totalframes", "framenum");
	}
	public mp3data_struct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends mp3data_struct implements Structure.ByReference {
	};
	public static class ByValue extends mp3data_struct implements Structure.ByValue {
	};
}
