package vavi.sound.midi.fluidsynth.jna.mod;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;


/**
 * JNA Wrapper for library <b>mod</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ModLibrary extends Library {

    String JNA_LIBRARY_NAME = "fluidsynth";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(ModLibrary.JNA_LIBRARY_NAME);
    ModLibrary INSTANCE = Native.load(ModLibrary.JNA_LIBRARY_NAME, ModLibrary.class);

    /**
     * Flags defining the polarity, mapping function and type of a modulator source.<br>
     * Compare with SoundFont 2.04 PDF section 8.2.<br>
     * Note: Bit values do not correspond to the SoundFont spec!  Also note that<br>
     * #FLUID_MOD_GC and #FLUID_MOD_CC are in the flags field instead of the source field.<br>
     * <i>native declaration : fluidsynth/mod.h:44</i><br>
     * enum values
     */
    interface fluid_mod_flags {

        /**
         * < Mapping function is positive<br>
         * <i>native declaration : fluidsynth/mod.h:46</i>
         */
        int FLUID_MOD_POSITIVE = 0;
        /**
         * < Mapping function is negative<br>
         * <i>native declaration : fluidsynth/mod.h:47</i>
         */
        int FLUID_MOD_NEGATIVE = 1;
        /**
         * < Mapping function is unipolar<br>
         * <i>native declaration : fluidsynth/mod.h:48</i>
         */
        int FLUID_MOD_UNIPOLAR = 0;
        /**
         * < Mapping function is bipolar<br>
         * <i>native declaration : fluidsynth/mod.h:49</i>
         */
        int FLUID_MOD_BIPOLAR = 2;
        /**
         * < Linear mapping function<br>
         * <i>native declaration : fluidsynth/mod.h:50</i>
         */
        int FLUID_MOD_LINEAR = 0;
        /**
         * < Concave mapping function<br>
         * <i>native declaration : fluidsynth/mod.h:51</i>
         */
        int FLUID_MOD_CONCAVE = 4;
        /**
         * < Convex mapping function<br>
         * <i>native declaration : fluidsynth/mod.h:52</i>
         */
        int FLUID_MOD_CONVEX = 8;
        /**
         * < Switch (on/off) mapping function<br>
         * <i>native declaration : fluidsynth/mod.h:53</i>
         */
        int FLUID_MOD_SWITCH = 12;
        /**
         * < General controller source type (#fluid_mod_src)<br>
         * <i>native declaration : fluidsynth/mod.h:54</i>
         */
        int FLUID_MOD_GC = 0;
        /**
         * < MIDI CC controller (source will be a MIDI CC number)<br>
         * <i>native declaration : fluidsynth/mod.h:55</i>
         */
        int FLUID_MOD_CC = 16;
        /**
         * < Custom non-standard sinus mapping function<br>
         * <i>native declaration : fluidsynth/mod.h:57</i>
         */
        int FLUID_MOD_SIN = 0x80;
    }

    /**
     * General controller (if #FLUID_MOD_GC in flags).  This<br>
     * corresponds to SoundFont 2.04 PDF section 8.2.1<br>
     * <i>native declaration : fluidsynth/mod.h:64</i><br>
     * enum values
     */
    interface fluid_mod_src {

        /**
         * < No source controller<br>
         * <i>native declaration : fluidsynth/mod.h:66</i>
         */
        int FLUID_MOD_NONE = 0;
        /**
         * < MIDI note-on velocity<br>
         * <i>native declaration : fluidsynth/mod.h:67</i>
         */
        int FLUID_MOD_VELOCITY = 2;
        /**
         * < MIDI note-on note number<br>
         * <i>native declaration : fluidsynth/mod.h:68</i>
         */
        int FLUID_MOD_KEY = 3;
        /**
         * < MIDI key pressure<br>
         * <i>native declaration : fluidsynth/mod.h:69</i>
         */
        int FLUID_MOD_KEYPRESSURE = 10;
        /**
         * < MIDI channel pressure<br>
         * <i>native declaration : fluidsynth/mod.h:70</i>
         */
        int FLUID_MOD_CHANNELPRESSURE = 13;
        /**
         * < Pitch wheel<br>
         * <i>native declaration : fluidsynth/mod.h:71</i>
         */
        int FLUID_MOD_PITCHWHEEL = 14;
        /**
         * < Pitch wheel sensitivity<br>
         * <i>native declaration : fluidsynth/mod.h:72</i>
         */
        int FLUID_MOD_PITCHWHEELSENS = 16;
    }

    /**
     * @startlifecycle{Modulator}<br> Original signature : <code>fluid_mod_t* new_fluid_mod()</code><br>
     * <i>native declaration : fluidsynth/mod.h:76</i>
     */
    PointerByReference new_fluid_mod();

    /**
     * Original signature : <code>void delete_fluid_mod(fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:77</i><br>
     *
     * @deprecated use the safer method {@link #delete_fluid_mod(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void delete_fluid_mod(Pointer mod);

    /**
     * Original signature : <code>void delete_fluid_mod(fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:77</i>
     */
    void delete_fluid_mod(PointerByReference mod);

    /**
     * @endlifecycle<br> Original signature : <code>size_t fluid_mod_sizeof()</code><br>
     * <i>native declaration : fluidsynth/mod.h:80</i>
     */
    NativeLong fluid_mod_sizeof();

    /**
     * Original signature : <code>void fluid_mod_set_source1(fluid_mod_t*, int, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:82</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_set_source1(com.sun.jna.ptr.PointerByReference, int, int)} instead
     */
    @Deprecated
    void fluid_mod_set_source1(Pointer mod, int src, int flags);

    /**
     * Original signature : <code>void fluid_mod_set_source1(fluid_mod_t*, int, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:82</i>
     */
    void fluid_mod_set_source1(PointerByReference mod, int src, int flags);

    /**
     * Original signature : <code>void fluid_mod_set_source2(fluid_mod_t*, int, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:83</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_set_source2(com.sun.jna.ptr.PointerByReference, int, int)} instead
     */
    @Deprecated
    void fluid_mod_set_source2(Pointer mod, int src, int flags);

    /**
     * Original signature : <code>void fluid_mod_set_source2(fluid_mod_t*, int, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:83</i>
     */
    void fluid_mod_set_source2(PointerByReference mod, int src, int flags);

    /**
     * Original signature : <code>void fluid_mod_set_dest(fluid_mod_t*, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:84</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_set_dest(com.sun.jna.ptr.PointerByReference, int)} instead
     */
    @Deprecated
    void fluid_mod_set_dest(Pointer mod, int dst);

    /**
     * Original signature : <code>void fluid_mod_set_dest(fluid_mod_t*, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:84</i>
     */
    void fluid_mod_set_dest(PointerByReference mod, int dst);

    /**
     * Original signature : <code>void fluid_mod_set_amount(fluid_mod_t*, double)</code><br>
     * <i>native declaration : fluidsynth/mod.h:85</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_set_amount(com.sun.jna.ptr.PointerByReference, double)} instead
     */
    @Deprecated
    void fluid_mod_set_amount(Pointer mod, double amount);

    /**
     * Original signature : <code>void fluid_mod_set_amount(fluid_mod_t*, double)</code><br>
     * <i>native declaration : fluidsynth/mod.h:85</i>
     */
    void fluid_mod_set_amount(PointerByReference mod, double amount);

    /**
     * Original signature : <code>int fluid_mod_get_source1(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:87</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_get_source1(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_mod_get_source1(Pointer mod);

    /**
     * Original signature : <code>int fluid_mod_get_source1(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:87</i>
     */
    int fluid_mod_get_source1(PointerByReference mod);

    /**
     * Original signature : <code>int fluid_mod_get_flags1(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:88</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_get_flags1(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_mod_get_flags1(Pointer mod);

    /**
     * Original signature : <code>int fluid_mod_get_flags1(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:88</i>
     */
    int fluid_mod_get_flags1(PointerByReference mod);

    /**
     * Original signature : <code>int fluid_mod_get_source2(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:89</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_get_source2(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_mod_get_source2(Pointer mod);

    /**
     * Original signature : <code>int fluid_mod_get_source2(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:89</i>
     */
    int fluid_mod_get_source2(PointerByReference mod);

    /**
     * Original signature : <code>int fluid_mod_get_flags2(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:90</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_get_flags2(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_mod_get_flags2(Pointer mod);

    /**
     * Original signature : <code>int fluid_mod_get_flags2(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:90</i>
     */
    int fluid_mod_get_flags2(PointerByReference mod);

    /**
     * Original signature : <code>int fluid_mod_get_dest(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:91</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_get_dest(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_mod_get_dest(Pointer mod);

    /**
     * Original signature : <code>int fluid_mod_get_dest(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:91</i>
     */
    int fluid_mod_get_dest(PointerByReference mod);

    /**
     * Original signature : <code>double fluid_mod_get_amount(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:92</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_get_amount(com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    double fluid_mod_get_amount(Pointer mod);

    /**
     * Original signature : <code>double fluid_mod_get_amount(const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:92</i>
     */
    double fluid_mod_get_amount(PointerByReference mod);

    /**
     * Original signature : <code>int fluid_mod_test_identity(const fluid_mod_t*, const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:94</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_test_identity(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    int fluid_mod_test_identity(Pointer mod1, Pointer mod2);

    /**
     * Original signature : <code>int fluid_mod_test_identity(const fluid_mod_t*, const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:94</i>
     */
    int fluid_mod_test_identity(PointerByReference mod1, PointerByReference mod2);

    /**
     * Original signature : <code>int fluid_mod_has_source(const fluid_mod_t*, int, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:95</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_has_source(com.sun.jna.ptr.PointerByReference, int, int)} instead
     */
    @Deprecated
    int fluid_mod_has_source(Pointer mod, int cc, int ctrl);

    /**
     * Original signature : <code>int fluid_mod_has_source(const fluid_mod_t*, int, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:95</i>
     */
    int fluid_mod_has_source(PointerByReference mod, int cc, int ctrl);

    /**
     * Original signature : <code>int fluid_mod_has_dest(const fluid_mod_t*, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:96</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_has_dest(com.sun.jna.ptr.PointerByReference, int)} instead
     */
    @Deprecated
    int fluid_mod_has_dest(Pointer mod, int gen);

    /**
     * Original signature : <code>int fluid_mod_has_dest(const fluid_mod_t*, int)</code><br>
     * <i>native declaration : fluidsynth/mod.h:96</i>
     */
    int fluid_mod_has_dest(PointerByReference mod, int gen);

    /**
     * Original signature : <code>void fluid_mod_clone(fluid_mod_t*, const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:98</i><br>
     *
     * @deprecated use the safer method {@link #fluid_mod_clone(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
     */
    @Deprecated
    void fluid_mod_clone(Pointer mod, Pointer src);

    /**
     * Original signature : <code>void fluid_mod_clone(fluid_mod_t*, const fluid_mod_t*)</code><br>
     * <i>native declaration : fluidsynth/mod.h:98</i>
     */
    void fluid_mod_clone(PointerByReference mod, PointerByReference src);
}
