<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.tritonus</groupId>
    <artifactId>tritonus</artifactId>
    <version>0.3.15</version>
  </parent>

  <artifactId>tritonus-saol</artifactId>
  <packaging>jar</packaging>

  <name>Tritonus SAOL Module</name>

  <properties>
    <gensource.dir>${project.build.directory}/generated-sources</gensource.dir>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${gensource.dir}/sablecc</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>com.github.verylazyboy</groupId>
        <artifactId>sablecc-maven-plugin</artifactId>
        <version>2.0-beta.2</version>
        <dependencies>
          <dependency>
            <groupId>com.github.verylazyboy</groupId>
            <artifactId>sablecc-maven-port</artifactId>
            <version>3.7</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>saol grammar</id>
            <configuration>
              <grammar>${project.basedir}/src/main/sablecc/saol.grammar</grammar>
              <destination>${gensource.dir}/sablecc</destination>
            </configuration>
            <goals>
              <goal>sablecc</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.tritonus</groupId>
      <artifactId>tritonus-remaining</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.bcel</groupId>
      <artifactId>bcel</artifactId>
      <version>6.11.0</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
