package vavi.sound.midi.fluidsynth.jna;
import com.sun.jna.Callback;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;
/**
 * JNA Wrapper for library <b></b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Library extends com.sun.jna.Library {
	String JNA_LIBRARY_NAME = "fluidsynth";
	NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Library.JNA_LIBRARY_NAME);
	Library INSTANCE = Native.load(Library.JNA_LIBRARY_NAME, Library.class);
	/** <i>native declaration : fluidsynth/seq.h</i> */
	public interface fluid_event_callback_t extends Callback {
		void apply(int time, Pointer event, Pointer seq, Pointer data);
	};
	/**
	 * @startlifecycle{MIDI Sequencer}<br>
	 * Original signature : <code>fluid_sequencer_t* new_fluid_sequencer()</code><br>
	 * <i>native declaration : fluidsynth/seq.h:62</i>
	 */
	PointerByReference new_fluid_sequencer();
	/**
	 * Original signature : <code>fluid_sequencer_t* new_fluid_sequencer2(int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:63</i>
	 */
	PointerByReference new_fluid_sequencer2(int use_system_timer);
	/**
	 * Original signature : <code>void delete_fluid_sequencer(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:64</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_sequencer(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_sequencer(Pointer seq);
	/**
	 * Original signature : <code>void delete_fluid_sequencer(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:64</i>
	 */
	void delete_fluid_sequencer(PointerByReference seq);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_sequencer_get_use_system_timer(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:67</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_get_use_system_timer(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_sequencer_get_use_system_timer(Pointer seq);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>int fluid_sequencer_get_use_system_timer(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:67</i>
	 */
	int fluid_sequencer_get_use_system_timer(PointerByReference seq);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_sequencer_register_client(fluid_sequencer_t*, const char*, fluid_event_callback_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:69</i><br>
	 * @deprecated use the safer methods {@link #fluid_sequencer_register_client(com.sun.jna.ptr.PointerByReference, java.lang.String, vavi.sound.midi.fluidsynth.jna.Library.fluid_event_callback_t, com.sun.jna.Pointer)} and {@link #fluid_sequencer_register_client(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, vavi.sound.midi.fluidsynth.jna.Library.fluid_event_callback_t, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	short fluid_sequencer_register_client(Pointer seq, Pointer name, Library.fluid_event_callback_t callback, Pointer data);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_sequencer_register_client(fluid_sequencer_t*, const char*, fluid_event_callback_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:69</i>
	 */
	short fluid_sequencer_register_client(PointerByReference seq, String name, Library.fluid_event_callback_t callback, Pointer data);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_sequencer_register_client(fluid_sequencer_t*, const char*, fluid_event_callback_t, void*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:69</i>
	 */
	short fluid_sequencer_register_client(PointerByReference seq, Pointer name, Library.fluid_event_callback_t callback, Pointer data);
	/**
	 * Original signature : <code>void fluid_sequencer_unregister_client(fluid_sequencer_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:71</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_unregister_client(com.sun.jna.ptr.PointerByReference, short)} instead
	 */
	@Deprecated 
	void fluid_sequencer_unregister_client(Pointer seq, short id);
	/**
	 * Original signature : <code>void fluid_sequencer_unregister_client(fluid_sequencer_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:71</i>
	 */
	void fluid_sequencer_unregister_client(PointerByReference seq, short id);
	/**
	 * Original signature : <code>int fluid_sequencer_count_clients(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:72</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_count_clients(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_sequencer_count_clients(Pointer seq);
	/**
	 * Original signature : <code>int fluid_sequencer_count_clients(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:72</i>
	 */
	int fluid_sequencer_count_clients(PointerByReference seq);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_sequencer_get_client_id(fluid_sequencer_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:73</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_get_client_id(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	short fluid_sequencer_get_client_id(Pointer seq, int index);
	/**
	 * Original signature : <code>fluid_seq_id_t fluid_sequencer_get_client_id(fluid_sequencer_t*, int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:73</i>
	 */
	short fluid_sequencer_get_client_id(PointerByReference seq, int index);
	/**
	 * Original signature : <code>char* fluid_sequencer_get_client_name(fluid_sequencer_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:74</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_get_client_name(com.sun.jna.ptr.PointerByReference, short)} instead
	 */
	@Deprecated 
	Pointer fluid_sequencer_get_client_name(Pointer seq, short id);
	/**
	 * Original signature : <code>char* fluid_sequencer_get_client_name(fluid_sequencer_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:74</i>
	 */
	Pointer fluid_sequencer_get_client_name(PointerByReference seq, short id);
	/**
	 * Original signature : <code>int fluid_sequencer_client_is_dest(fluid_sequencer_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:75</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_client_is_dest(com.sun.jna.ptr.PointerByReference, short)} instead
	 */
	@Deprecated 
	int fluid_sequencer_client_is_dest(Pointer seq, short id);
	/**
	 * Original signature : <code>int fluid_sequencer_client_is_dest(fluid_sequencer_t*, fluid_seq_id_t)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:75</i>
	 */
	int fluid_sequencer_client_is_dest(PointerByReference seq, short id);
	/**
	 * Original signature : <code>void fluid_sequencer_process(fluid_sequencer_t*, unsigned int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:76</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_process(com.sun.jna.ptr.PointerByReference, int)} instead
	 */
	@Deprecated 
	void fluid_sequencer_process(Pointer seq, int msec);
	/**
	 * Original signature : <code>void fluid_sequencer_process(fluid_sequencer_t*, unsigned int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:76</i>
	 */
	void fluid_sequencer_process(PointerByReference seq, int msec);
	/**
	 * Original signature : <code>void fluid_sequencer_send_now(fluid_sequencer_t*, fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:77</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_send_now(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void fluid_sequencer_send_now(Pointer seq, Pointer evt);
	/**
	 * Original signature : <code>void fluid_sequencer_send_now(fluid_sequencer_t*, fluid_event_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:77</i>
	 */
	void fluid_sequencer_send_now(PointerByReference seq, PointerByReference evt);
	/**
	 * Original signature : <code>int fluid_sequencer_send_at(fluid_sequencer_t*, fluid_event_t*, unsigned int, int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:79</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_send_at(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, int, int)} instead
	 */
	@Deprecated 
	int fluid_sequencer_send_at(Pointer seq, Pointer evt, int time, int absolute);
	/**
	 * Original signature : <code>int fluid_sequencer_send_at(fluid_sequencer_t*, fluid_event_t*, unsigned int, int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:79</i>
	 */
	int fluid_sequencer_send_at(PointerByReference seq, PointerByReference evt, int time, int absolute);
	/**
	 * Original signature : <code>void fluid_sequencer_remove_events(fluid_sequencer_t*, fluid_seq_id_t, fluid_seq_id_t, int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:82</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_remove_events(com.sun.jna.ptr.PointerByReference, short, short, int)} instead
	 */
	@Deprecated 
	void fluid_sequencer_remove_events(Pointer seq, short source, short dest, int type);
	/**
	 * Original signature : <code>void fluid_sequencer_remove_events(fluid_sequencer_t*, fluid_seq_id_t, fluid_seq_id_t, int)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:82</i>
	 */
	void fluid_sequencer_remove_events(PointerByReference seq, short source, short dest, int type);
	/**
	 * Original signature : <code>int fluid_sequencer_get_tick(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:83</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_get_tick(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_sequencer_get_tick(Pointer seq);
	/**
	 * Original signature : <code>int fluid_sequencer_get_tick(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:83</i>
	 */
	int fluid_sequencer_get_tick(PointerByReference seq);
	/**
	 * Original signature : <code>void fluid_sequencer_set_time_scale(fluid_sequencer_t*, double)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:84</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_set_time_scale(com.sun.jna.ptr.PointerByReference, double)} instead
	 */
	@Deprecated 
	void fluid_sequencer_set_time_scale(Pointer seq, double scale);
	/**
	 * Original signature : <code>void fluid_sequencer_set_time_scale(fluid_sequencer_t*, double)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:84</i>
	 */
	void fluid_sequencer_set_time_scale(PointerByReference seq, double scale);
	/**
	 * Original signature : <code>double fluid_sequencer_get_time_scale(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:85</i><br>
	 * @deprecated use the safer method {@link #fluid_sequencer_get_time_scale(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	double fluid_sequencer_get_time_scale(Pointer seq);
	/**
	 * Original signature : <code>double fluid_sequencer_get_time_scale(fluid_sequencer_t*)</code><br>
	 * <i>native declaration : fluidsynth/seq.h:85</i>
	 */
	double fluid_sequencer_get_time_scale(PointerByReference seq);
	public static class fluid_event_t extends PointerType {
		public fluid_event_t(Pointer address) {
			super(address);
		}
		public fluid_event_t() {
			super();
		}
	};
	public static class fluid_sequencer_t extends PointerType {
		public fluid_sequencer_t(Pointer address) {
			super(address);
		}
		public fluid_sequencer_t() {
			super();
		}
	};
}
