package vavi.sound.midi.fluidsynth.jna.shell;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;
import java.nio.ByteBuffer;
/**
 * JNA Wrapper for library <b>shell</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ShellLibrary extends Library {
	String JNA_LIBRARY_NAME = "fluidsynth";
	NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(ShellLibrary.JNA_LIBRARY_NAME);
	ShellLibrary INSTANCE = Native.load(ShellLibrary.JNA_LIBRARY_NAME, ShellLibrary.class);
	/**
	 * @defgroup command_interface Command Interface<br>
	 * Control and configuration interface<br>
	 * The command interface allows you to send textual commands to<br>
	 * the synthesizer, to parse a command file, or to read commands<br>
	 * from the stdin or other input streams (like a TCP socket).<br>
	 * For a full list of available commands, type \c help in the<br>
	 * \ref command_shell or send the same command via a command handler.<br>
	 * Further documentation can be found at<br>
	 * https://github.com/FluidSynth/fluidsynth/wiki/UserManual#shell-commands<br>
	 * @{<br>
	 * Original signature : <code>fluid_istream_t fluid_get_stdin()</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:46</i>
	 */
	int fluid_get_stdin();
	/**
	 * Original signature : <code>fluid_ostream_t fluid_get_stdout()</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:47</i>
	 */
	int fluid_get_stdout();
	/**
	 * Original signature : <code>char* fluid_get_userconf(char*, int)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:48</i><br>
	 * @deprecated use the safer methods {@link #fluid_get_userconf(java.nio.ByteBuffer, int)} and {@link #fluid_get_userconf(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	Pointer fluid_get_userconf(Pointer buf, int len);
	/**
	 * Original signature : <code>char* fluid_get_userconf(char*, int)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:48</i>
	 */
	Pointer fluid_get_userconf(ByteBuffer buf, int len);
	/**
	 * Original signature : <code>char* fluid_get_sysconf(char*, int)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:49</i><br>
	 * @deprecated use the safer methods {@link #fluid_get_sysconf(java.nio.ByteBuffer, int)} and {@link #fluid_get_sysconf(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	Pointer fluid_get_sysconf(Pointer buf, int len);
	/**
	 * Original signature : <code>char* fluid_get_sysconf(char*, int)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:49</i>
	 */
	Pointer fluid_get_sysconf(ByteBuffer buf, int len);
	/**
	 * @startlifecycle{Command Handler}<br>
	 * Original signature : <code>fluid_cmd_handler_t* new_fluid_cmd_handler(fluid_synth_t*, fluid_midi_router_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:63</i><br>
	 * @deprecated use the safer method {@link #new_fluid_cmd_handler(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_cmd_handler(Pointer synth, Pointer router);
	/**
	 * @startlifecycle{Command Handler}<br>
	 * Original signature : <code>fluid_cmd_handler_t* new_fluid_cmd_handler(fluid_synth_t*, fluid_midi_router_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:63</i>
	 */
	PointerByReference new_fluid_cmd_handler(PointerByReference synth, PointerByReference router);
	/**
	 * Original signature : <code>fluid_cmd_handler_t* new_fluid_cmd_handler2(fluid_settings_t*, fluid_synth_t*, fluid_midi_router_t*, fluid_player_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:66</i><br>
	 * @deprecated use the safer method {@link #new_fluid_cmd_handler2(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_cmd_handler2(Pointer settings, Pointer synth, Pointer router, Pointer player);
	/**
	 * Original signature : <code>fluid_cmd_handler_t* new_fluid_cmd_handler2(fluid_settings_t*, fluid_synth_t*, fluid_midi_router_t*, fluid_player_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:66</i>
	 */
	PointerByReference new_fluid_cmd_handler2(PointerByReference settings, PointerByReference synth, PointerByReference router, PointerByReference player);
	/**
	 * Original signature : <code>void delete_fluid_cmd_handler(fluid_cmd_handler_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:70</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_cmd_handler(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_cmd_handler(Pointer handler);
	/**
	 * Original signature : <code>void delete_fluid_cmd_handler(fluid_cmd_handler_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:70</i>
	 */
	void delete_fluid_cmd_handler(PointerByReference handler);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>void fluid_cmd_handler_set_synth(fluid_cmd_handler_t*, fluid_synth_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:74</i><br>
	 * @deprecated use the safer method {@link #fluid_cmd_handler_set_synth(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void fluid_cmd_handler_set_synth(Pointer handler, Pointer synth);
	/**
	 * @endlifecycle<br>
	 * Original signature : <code>void fluid_cmd_handler_set_synth(fluid_cmd_handler_t*, fluid_synth_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:74</i>
	 */
	void fluid_cmd_handler_set_synth(PointerByReference handler, PointerByReference synth);
	/**
	 * Original signature : <code>int fluid_command(fluid_cmd_handler_t*, const char*, fluid_ostream_t)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:77</i><br>
	 * @deprecated use the safer methods {@link #fluid_command(com.sun.jna.ptr.PointerByReference, java.lang.String, int)} and {@link #fluid_command(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int fluid_command(Pointer handler, Pointer cmd, int out);
	/**
	 * Original signature : <code>int fluid_command(fluid_cmd_handler_t*, const char*, fluid_ostream_t)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:77</i>
	 */
	int fluid_command(PointerByReference handler, String cmd, int out);
	/**
	 * Original signature : <code>int fluid_command(fluid_cmd_handler_t*, const char*, fluid_ostream_t)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:77</i>
	 */
	int fluid_command(PointerByReference handler, Pointer cmd, int out);
	/**
	 * Original signature : <code>int fluid_source(fluid_cmd_handler_t*, const char*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:80</i><br>
	 * @deprecated use the safer methods {@link #fluid_source(com.sun.jna.ptr.PointerByReference, java.lang.String)} and {@link #fluid_source(com.sun.jna.ptr.PointerByReference, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int fluid_source(Pointer handler, Pointer filename);
	/**
	 * Original signature : <code>int fluid_source(fluid_cmd_handler_t*, const char*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:80</i>
	 */
	int fluid_source(PointerByReference handler, String filename);
	/**
	 * Original signature : <code>int fluid_source(fluid_cmd_handler_t*, const char*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:80</i>
	 */
	int fluid_source(PointerByReference handler, Pointer filename);
	/**
	 * @startlifecycle{Command Shell}<br>
	 * Original signature : <code>fluid_shell_t* new_fluid_shell(fluid_settings_t*, fluid_cmd_handler_t*, fluid_istream_t, fluid_ostream_t, int)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:100</i><br>
	 * @deprecated use the safer method {@link #new_fluid_shell(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, int, int, int)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_shell(Pointer settings, Pointer handler, int in, int out, int thread);
	/**
	 * @startlifecycle{Command Shell}<br>
	 * Original signature : <code>fluid_shell_t* new_fluid_shell(fluid_settings_t*, fluid_cmd_handler_t*, fluid_istream_t, fluid_ostream_t, int)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:100</i>
	 */
	PointerByReference new_fluid_shell(PointerByReference settings, PointerByReference handler, int in, int out, int thread);
	/**
	 * Original signature : <code>void fluid_usershell(fluid_settings_t*, fluid_cmd_handler_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:104</i><br>
	 * @deprecated use the safer method {@link #fluid_usershell(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void fluid_usershell(Pointer settings, Pointer handler);
	/**
	 * Original signature : <code>void fluid_usershell(fluid_settings_t*, fluid_cmd_handler_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:104</i>
	 */
	void fluid_usershell(PointerByReference settings, PointerByReference handler);
	/**
	 * Original signature : <code>void delete_fluid_shell(fluid_shell_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:106</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_shell(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_shell(Pointer shell);
	/**
	 * Original signature : <code>void delete_fluid_shell(fluid_shell_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:106</i>
	 */
	void delete_fluid_shell(PointerByReference shell);
	/**
	 * @startlifecycle{Command Server}<br>
	 * Original signature : <code>fluid_server_t* new_fluid_server(fluid_settings_t*, fluid_synth_t*, fluid_midi_router_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:131</i><br>
	 * @deprecated use the safer method {@link #new_fluid_server(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_server(Pointer settings, Pointer synth, Pointer router);
	/**
	 * @startlifecycle{Command Server}<br>
	 * Original signature : <code>fluid_server_t* new_fluid_server(fluid_settings_t*, fluid_synth_t*, fluid_midi_router_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:131</i>
	 */
	PointerByReference new_fluid_server(PointerByReference settings, PointerByReference synth, PointerByReference router);
	/**
	 * Original signature : <code>fluid_server_t* new_fluid_server2(fluid_settings_t*, fluid_synth_t*, fluid_midi_router_t*, fluid_player_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:135</i><br>
	 * @deprecated use the safer method {@link #new_fluid_server2(com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference, com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	PointerByReference new_fluid_server2(Pointer settings, Pointer synth, Pointer router, Pointer player);
	/**
	 * Original signature : <code>fluid_server_t* new_fluid_server2(fluid_settings_t*, fluid_synth_t*, fluid_midi_router_t*, fluid_player_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:135</i>
	 */
	PointerByReference new_fluid_server2(PointerByReference settings, PointerByReference synth, PointerByReference router, PointerByReference player);
	/**
	 * Original signature : <code>void delete_fluid_server(fluid_server_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:139</i><br>
	 * @deprecated use the safer method {@link #delete_fluid_server(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	void delete_fluid_server(Pointer server);
	/**
	 * Original signature : <code>void delete_fluid_server(fluid_server_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:139</i>
	 */
	void delete_fluid_server(PointerByReference server);
	/**
	 * Original signature : <code>int fluid_server_join(fluid_server_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:141</i><br>
	 * @deprecated use the safer method {@link #fluid_server_join(com.sun.jna.ptr.PointerByReference)} instead
	 */
	@Deprecated 
	int fluid_server_join(Pointer server);
	/**
	 * Original signature : <code>int fluid_server_join(fluid_server_t*)</code><br>
	 * <i>native declaration : include/fluidsynth/shell.h:141</i>
	 */
	int fluid_server_join(PointerByReference server);
	public static class fluid_cmd_handler_t extends PointerType {
		public fluid_cmd_handler_t(Pointer address) {
			super(address);
		}
		public fluid_cmd_handler_t() {
			super();
		}
	};
	public static class fluid_server_t extends PointerType {
		public fluid_server_t(Pointer address) {
			super(address);
		}
		public fluid_server_t() {
			super();
		}
	};
	public static class fluid_shell_t extends PointerType {
		public fluid_shell_t(Pointer address) {
			super(address);
		}
		public fluid_shell_t() {
			super();
		}
	};
}
