package vavi.sound.midi.fluidsynth.jna.misc;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;


/**
 * JNA Wrapper for library <b>misc</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface MiscLibrary extends Library {

    String JNA_LIBRARY_NAME = "fluidsynth";
    NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(MiscLibrary.JNA_LIBRARY_NAME);
    MiscLibrary INSTANCE = Native.load(MiscLibrary.JNA_LIBRARY_NAME, MiscLibrary.class);
    /** <i>native declaration : fluidsynth/misc.h</i> */
    int FLUID_OK = (int) (0);
    /** <i>native declaration : fluidsynth/misc.h</i> */
    int FLUID_FAILED = (int) (-1);

    /**
     * Value that indicates failure, used by most libfluidsynth functions.<br>
     *
     * @note See #FLUID_OK for more details.<br>
     * @since 1.1.0<br>
     * Original signature : <code>int fluid_is_soundfont(const char*)</code><br>
     * <i>native declaration : fluidsynth/misc.h:68</i><br>
     * @deprecated use the safer methods {@link #fluid_is_soundfont(java.lang.String)} and {@link #fluid_is_soundfont(com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_is_soundfont(Pointer filename);

    /**
     * Value that indicates failure, used by most libfluidsynth functions.<br>
     *
     * @note See #FLUID_OK for more details.<br>
     * @since 1.1.0<br>
     * Original signature : <code>int fluid_is_soundfont(const char*)</code><br>
     * <i>native declaration : fluidsynth/misc.h:68</i>
     */
    int fluid_is_soundfont(String filename);

    /**
     * Original signature : <code>int fluid_is_midifile(const char*)</code><br>
     * <i>native declaration : fluidsynth/misc.h:69</i><br>
     *
     * @deprecated use the safer methods {@link #fluid_is_midifile(java.lang.String)} and {@link #fluid_is_midifile(com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int fluid_is_midifile(Pointer filename);

    /**
     * Original signature : <code>int fluid_is_midifile(const char*)</code><br>
     * <i>native declaration : fluidsynth/misc.h:69</i>
     */
    int fluid_is_midifile(String filename);

    /**
     * Original signature : <code>void fluid_free(void*)</code><br>
     * <i>native declaration : fluidsynth/misc.h:70</i>
     */
    void fluid_free(Pointer ptr);
}
